creation_rules:
  - path_regex: \.aria/credentials/secrets/.*\.enc\.yaml$
    age: age1ar7v0rm6kxlrm33slxkvt3qp25807pksav4ptpc0vyguekvhhprse68gja
    encrypted_regex: '^(key|token|api_key|secret|password|client_secret)$'

  - path_regex: \.aria/runtime/credentials/.*\.enc\.yaml$
    age: age1ar7v0rm6kxlrm33slxkvt3qp25807pksav4ptpc0vyguekvhhprse68gja
    encrypted_regex: '^(key|token|api_key|secret|password|client_secret|state)$'