// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agencies.sql

package db

import (
	"context"
	"database/sql"
)

const createAgency = `-- name: CreateAgency :one
INSERT INTO agencies (
    id,
    name,
    domain,
    description,
    status,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, name, domain, description, status, created_at, updated_at
`

type CreateAgencyParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Domain      string         `json:"domain"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateAgency(ctx context.Context, arg CreateAgencyParams) (Agency, error) {
	row := q.queryRow(ctx, q.createAgencyStmt, createAgency,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Description,
		arg.Status,
	)
	var i Agency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgency = `-- name: DeleteAgency :exec
DELETE FROM agencies
WHERE id = ?
`

func (q *Queries) DeleteAgency(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteAgencyStmt, deleteAgency, id)
	return err
}

const deleteAgencyState = `-- name: DeleteAgencyState :exec
DELETE FROM agency_states
WHERE agency_id = ?
`

func (q *Queries) DeleteAgencyState(ctx context.Context, agencyID string) error {
	_, err := q.exec(ctx, q.deleteAgencyStateStmt, deleteAgencyState, agencyID)
	return err
}

const getAgencyByID = `-- name: GetAgencyByID :one
SELECT id, name, domain, description, status, created_at, updated_at
FROM agencies
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgencyByID(ctx context.Context, id string) (Agency, error) {
	row := q.queryRow(ctx, q.getAgencyByIDStmt, getAgencyByID, id)
	var i Agency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgencyByName = `-- name: GetAgencyByName :one
SELECT id, name, domain, description, status, created_at, updated_at
FROM agencies
WHERE name = ? LIMIT 1
`

func (q *Queries) GetAgencyByName(ctx context.Context, name string) (Agency, error) {
	row := q.queryRow(ctx, q.getAgencyByNameStmt, getAgencyByName, name)
	var i Agency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgencyState = `-- name: GetAgencyState :one
SELECT id, agency_id, status, last_task_id, metrics, updated_at
FROM agency_states
WHERE agency_id = ? LIMIT 1
`

func (q *Queries) GetAgencyState(ctx context.Context, agencyID string) (AgencyState, error) {
	row := q.queryRow(ctx, q.getAgencyStateStmt, getAgencyState, agencyID)
	var i AgencyState
	err := row.Scan(
		&i.ID,
		&i.AgencyID,
		&i.Status,
		&i.LastTaskID,
		&i.Metrics,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgencies = `-- name: ListAgencies :many
SELECT id, name, domain, description, status, created_at, updated_at
FROM agencies
ORDER BY name ASC
`

func (q *Queries) ListAgencies(ctx context.Context) ([]Agency, error) {
	rows, err := q.query(ctx, q.listAgenciesStmt, listAgencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agency{}
	for rows.Next() {
		var i Agency
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgenciesByStatus = `-- name: ListAgenciesByStatus :many
SELECT id, name, domain, description, status, created_at, updated_at
FROM agencies
WHERE status = ?
ORDER BY name ASC
`

func (q *Queries) ListAgenciesByStatus(ctx context.Context, status string) ([]Agency, error) {
	rows, err := q.query(ctx, q.listAgenciesByStatusStmt, listAgenciesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agency{}
	for rows.Next() {
		var i Agency
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgencyStatus = `-- name: UpdateAgencyStatus :exec
UPDATE agencies
SET status = ?, updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateAgencyStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAgencyStatus(ctx context.Context, arg UpdateAgencyStatusParams) error {
	_, err := q.exec(ctx, q.updateAgencyStatusStmt, updateAgencyStatus, arg.Status, arg.ID)
	return err
}

const upsertAgencyState = `-- name: UpsertAgencyState :one
INSERT INTO agency_states (
    id,
    agency_id,
    status,
    last_task_id,
    metrics,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) ON CONFLICT (id) DO UPDATE SET
    status = excluded.status,
    last_task_id = excluded.last_task_id,
    metrics = excluded.metrics,
    updated_at = strftime('%s', 'now')
RETURNING id, agency_id, status, last_task_id, metrics, updated_at
`

type UpsertAgencyStateParams struct {
	ID         string         `json:"id"`
	AgencyID   string         `json:"agency_id"`
	Status     string         `json:"status"`
	LastTaskID sql.NullString `json:"last_task_id"`
	Metrics    sql.NullString `json:"metrics"`
}

func (q *Queries) UpsertAgencyState(ctx context.Context, arg UpsertAgencyStateParams) (AgencyState, error) {
	row := q.queryRow(ctx, q.upsertAgencyStateStmt, upsertAgencyState,
		arg.ID,
		arg.AgencyID,
		arg.Status,
		arg.LastTaskID,
		arg.Metrics,
	)
	var i AgencyState
	err := row.Scan(
		&i.ID,
		&i.AgencyID,
		&i.Status,
		&i.LastTaskID,
		&i.Metrics,
		&i.UpdatedAt,
	)
	return i, err
}
