// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addTaskDependencyStmt, err = db.PrepareContext(ctx, addTaskDependency); err != nil {
		return nil, fmt.Errorf("error preparing query AddTaskDependency: %w", err)
	}
	if q.cancelTaskStmt, err = db.PrepareContext(ctx, cancelTask); err != nil {
		return nil, fmt.Errorf("error preparing query CancelTask: %w", err)
	}
	if q.countEpisodeEmbeddingsStmt, err = db.PrepareContext(ctx, countEpisodeEmbeddings); err != nil {
		return nil, fmt.Errorf("error preparing query CountEpisodeEmbeddings: %w", err)
	}
	if q.countEpisodesByOutcomeStmt, err = db.PrepareContext(ctx, countEpisodesByOutcome); err != nil {
		return nil, fmt.Errorf("error preparing query CountEpisodesByOutcome: %w", err)
	}
	if q.countFactEmbeddingsStmt, err = db.PrepareContext(ctx, countFactEmbeddings); err != nil {
		return nil, fmt.Errorf("error preparing query CountFactEmbeddings: %w", err)
	}
	if q.countTasksByStatusStmt, err = db.PrepareContext(ctx, countTasksByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query CountTasksByStatus: %w", err)
	}
	if q.createAgencyStmt, err = db.PrepareContext(ctx, createAgency); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAgency: %w", err)
	}
	if q.createEpisodeStmt, err = db.PrepareContext(ctx, createEpisode); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEpisode: %w", err)
	}
	if q.createEpisodeEmbeddingStmt, err = db.PrepareContext(ctx, createEpisodeEmbedding); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEpisodeEmbedding: %w", err)
	}
	if q.createFactStmt, err = db.PrepareContext(ctx, createFact); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFact: %w", err)
	}
	if q.createFactEmbeddingStmt, err = db.PrepareContext(ctx, createFactEmbedding); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFactEmbedding: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createGuardrailAuditEntryStmt, err = db.PrepareContext(ctx, createGuardrailAuditEntry); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGuardrailAuditEntry: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createPermissionRequestStmt, err = db.PrepareContext(ctx, createPermissionRequest); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePermissionRequest: %w", err)
	}
	if q.createPermissionResponseStmt, err = db.PrepareContext(ctx, createPermissionResponse); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePermissionResponse: %w", err)
	}
	if q.createPermissionRuleStmt, err = db.PrepareContext(ctx, createPermissionRule); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePermissionRule: %w", err)
	}
	if q.createProcedureStmt, err = db.PrepareContext(ctx, createProcedure); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProcedure: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createTaskStmt, err = db.PrepareContext(ctx, createTask); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTask: %w", err)
	}
	if q.createTaskEventStmt, err = db.PrepareContext(ctx, createTaskEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTaskEvent: %w", err)
	}
	if q.deleteAgencyStmt, err = db.PrepareContext(ctx, deleteAgency); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAgency: %w", err)
	}
	if q.deleteAgencyStateStmt, err = db.PrepareContext(ctx, deleteAgencyState); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAgencyState: %w", err)
	}
	if q.deleteEpisodeStmt, err = db.PrepareContext(ctx, deleteEpisode); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEpisode: %w", err)
	}
	if q.deleteEpisodeEmbeddingStmt, err = db.PrepareContext(ctx, deleteEpisodeEmbedding); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEpisodeEmbedding: %w", err)
	}
	if q.deleteExpiredContextsStmt, err = db.PrepareContext(ctx, deleteExpiredContexts); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredContexts: %w", err)
	}
	if q.deleteExpiredPermissionRulesStmt, err = db.PrepareContext(ctx, deleteExpiredPermissionRules); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredPermissionRules: %w", err)
	}
	if q.deleteFactStmt, err = db.PrepareContext(ctx, deleteFact); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFact: %w", err)
	}
	if q.deleteFactEmbeddingStmt, err = db.PrepareContext(ctx, deleteFactEmbedding); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFactEmbedding: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteOldEpisodesStmt, err = db.PrepareContext(ctx, deleteOldEpisodes); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOldEpisodes: %w", err)
	}
	if q.deleteOldGuardrailAuditStmt, err = db.PrepareContext(ctx, deleteOldGuardrailAudit); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOldGuardrailAudit: %w", err)
	}
	if q.deleteOldPermissionRequestsStmt, err = db.PrepareContext(ctx, deleteOldPermissionRequests); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOldPermissionRequests: %w", err)
	}
	if q.deletePermissionRuleStmt, err = db.PrepareContext(ctx, deletePermissionRule); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePermissionRule: %w", err)
	}
	if q.deleteProcedureStmt, err = db.PrepareContext(ctx, deleteProcedure); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProcedure: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.deleteTaskStmt, err = db.PrepareContext(ctx, deleteTask); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTask: %w", err)
	}
	if q.deleteWorkingContextStmt, err = db.PrepareContext(ctx, deleteWorkingContext); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteWorkingContext: %w", err)
	}
	if q.getAgencyByIDStmt, err = db.PrepareContext(ctx, getAgencyByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgencyByID: %w", err)
	}
	if q.getAgencyByNameStmt, err = db.PrepareContext(ctx, getAgencyByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgencyByName: %w", err)
	}
	if q.getAgencyStateStmt, err = db.PrepareContext(ctx, getAgencyState); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgencyState: %w", err)
	}
	if q.getDependentTasksStmt, err = db.PrepareContext(ctx, getDependentTasks); err != nil {
		return nil, fmt.Errorf("error preparing query GetDependentTasks: %w", err)
	}
	if q.getEpisodeByIDStmt, err = db.PrepareContext(ctx, getEpisodeByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetEpisodeByID: %w", err)
	}
	if q.getEpisodeEmbeddingStmt, err = db.PrepareContext(ctx, getEpisodeEmbedding); err != nil {
		return nil, fmt.Errorf("error preparing query GetEpisodeEmbedding: %w", err)
	}
	if q.getEpisodeEmbeddingByHashStmt, err = db.PrepareContext(ctx, getEpisodeEmbeddingByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetEpisodeEmbeddingByHash: %w", err)
	}
	if q.getFactByIDStmt, err = db.PrepareContext(ctx, getFactByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFactByID: %w", err)
	}
	if q.getFactEmbeddingStmt, err = db.PrepareContext(ctx, getFactEmbedding); err != nil {
		return nil, fmt.Errorf("error preparing query GetFactEmbedding: %w", err)
	}
	if q.getFactEmbeddingByHashStmt, err = db.PrepareContext(ctx, getFactEmbeddingByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetFactEmbeddingByHash: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getGuardrailBudgetStmt, err = db.PrepareContext(ctx, getGuardrailBudget); err != nil {
		return nil, fmt.Errorf("error preparing query GetGuardrailBudget: %w", err)
	}
	if q.getGuardrailPreferencesStmt, err = db.PrepareContext(ctx, getGuardrailPreferences); err != nil {
		return nil, fmt.Errorf("error preparing query GetGuardrailPreferences: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getPermissionRequestByIDStmt, err = db.PrepareContext(ctx, getPermissionRequestByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPermissionRequestByID: %w", err)
	}
	if q.getPermissionResponseByRequestIDStmt, err = db.PrepareContext(ctx, getPermissionResponseByRequestID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPermissionResponseByRequestID: %w", err)
	}
	if q.getPermissionRuleByIDStmt, err = db.PrepareContext(ctx, getPermissionRuleByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPermissionRuleByID: %w", err)
	}
	if q.getProcedureByIDStmt, err = db.PrepareContext(ctx, getProcedureByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProcedureByID: %w", err)
	}
	if q.getProcedureByNameStmt, err = db.PrepareContext(ctx, getProcedureByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetProcedureByName: %w", err)
	}
	if q.getRecentTaskEventsStmt, err = db.PrepareContext(ctx, getRecentTaskEvents); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentTaskEvents: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getTaskByIDStmt, err = db.PrepareContext(ctx, getTaskByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTaskByID: %w", err)
	}
	if q.getTaskDependenciesStmt, err = db.PrepareContext(ctx, getTaskDependencies); err != nil {
		return nil, fmt.Errorf("error preparing query GetTaskDependencies: %w", err)
	}
	if q.getTaskEventsStmt, err = db.PrepareContext(ctx, getTaskEvents); err != nil {
		return nil, fmt.Errorf("error preparing query GetTaskEvents: %w", err)
	}
	if q.getWorkingContextStmt, err = db.PrepareContext(ctx, getWorkingContext); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorkingContext: %w", err)
	}
	if q.incrementFactUsageStmt, err = db.PrepareContext(ctx, incrementFactUsage); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementFactUsage: %w", err)
	}
	if q.listAgenciesStmt, err = db.PrepareContext(ctx, listAgencies); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgencies: %w", err)
	}
	if q.listAgenciesByStatusStmt, err = db.PrepareContext(ctx, listAgenciesByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgenciesByStatus: %w", err)
	}
	if q.listEpisodeEmbeddingsStmt, err = db.PrepareContext(ctx, listEpisodeEmbeddings); err != nil {
		return nil, fmt.Errorf("error preparing query ListEpisodeEmbeddings: %w", err)
	}
	if q.listEpisodesStmt, err = db.PrepareContext(ctx, listEpisodes); err != nil {
		return nil, fmt.Errorf("error preparing query ListEpisodes: %w", err)
	}
	if q.listEpisodesByAgencyStmt, err = db.PrepareContext(ctx, listEpisodesByAgency); err != nil {
		return nil, fmt.Errorf("error preparing query ListEpisodesByAgency: %w", err)
	}
	if q.listEpisodesBySessionStmt, err = db.PrepareContext(ctx, listEpisodesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListEpisodesBySession: %w", err)
	}
	if q.listFactEmbeddingsStmt, err = db.PrepareContext(ctx, listFactEmbeddings); err != nil {
		return nil, fmt.Errorf("error preparing query ListFactEmbeddings: %w", err)
	}
	if q.listFactsByCategoryStmt, err = db.PrepareContext(ctx, listFactsByCategory); err != nil {
		return nil, fmt.Errorf("error preparing query ListFactsByCategory: %w", err)
	}
	if q.listFactsByDomainStmt, err = db.PrepareContext(ctx, listFactsByDomain); err != nil {
		return nil, fmt.Errorf("error preparing query ListFactsByDomain: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listGuardrailAuditByTimeRangeStmt, err = db.PrepareContext(ctx, listGuardrailAuditByTimeRange); err != nil {
		return nil, fmt.Errorf("error preparing query ListGuardrailAuditByTimeRange: %w", err)
	}
	if q.listGuardrailAuditByTypeStmt, err = db.PrepareContext(ctx, listGuardrailAuditByType); err != nil {
		return nil, fmt.Errorf("error preparing query ListGuardrailAuditByType: %w", err)
	}
	if q.listGuardrailBudgetsStmt, err = db.PrepareContext(ctx, listGuardrailBudgets); err != nil {
		return nil, fmt.Errorf("error preparing query ListGuardrailBudgets: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listPendingTasksStmt, err = db.PrepareContext(ctx, listPendingTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingTasks: %w", err)
	}
	if q.listPermissionRequestsByAgencyStmt, err = db.PrepareContext(ctx, listPermissionRequestsByAgency); err != nil {
		return nil, fmt.Errorf("error preparing query ListPermissionRequestsByAgency: %w", err)
	}
	if q.listPermissionRequestsByAgentStmt, err = db.PrepareContext(ctx, listPermissionRequestsByAgent); err != nil {
		return nil, fmt.Errorf("error preparing query ListPermissionRequestsByAgent: %w", err)
	}
	if q.listPermissionRulesByAgencyStmt, err = db.PrepareContext(ctx, listPermissionRulesByAgency); err != nil {
		return nil, fmt.Errorf("error preparing query ListPermissionRulesByAgency: %w", err)
	}
	if q.listProceduresStmt, err = db.PrepareContext(ctx, listProcedures); err != nil {
		return nil, fmt.Errorf("error preparing query ListProcedures: %w", err)
	}
	if q.listProceduresByTriggerStmt, err = db.PrepareContext(ctx, listProceduresByTrigger); err != nil {
		return nil, fmt.Errorf("error preparing query ListProceduresByTrigger: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listTasksStmt, err = db.PrepareContext(ctx, listTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasks: %w", err)
	}
	if q.listTasksByAgencyStmt, err = db.PrepareContext(ctx, listTasksByAgency); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasksByAgency: %w", err)
	}
	if q.listTasksByStatusStmt, err = db.PrepareContext(ctx, listTasksByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasksByStatus: %w", err)
	}
	if q.removeTaskDependencyStmt, err = db.PrepareContext(ctx, removeTaskDependency); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveTaskDependency: %w", err)
	}
	if q.resetGuardrailBudgetsStmt, err = db.PrepareContext(ctx, resetGuardrailBudgets); err != nil {
		return nil, fmt.Errorf("error preparing query ResetGuardrailBudgets: %w", err)
	}
	if q.saveWorkingContextStmt, err = db.PrepareContext(ctx, saveWorkingContext); err != nil {
		return nil, fmt.Errorf("error preparing query SaveWorkingContext: %w", err)
	}
	if q.searchEpisodesStmt, err = db.PrepareContext(ctx, searchEpisodes); err != nil {
		return nil, fmt.Errorf("error preparing query SearchEpisodes: %w", err)
	}
	if q.searchEpisodesByAgentStmt, err = db.PrepareContext(ctx, searchEpisodesByAgent); err != nil {
		return nil, fmt.Errorf("error preparing query SearchEpisodesByAgent: %w", err)
	}
	if q.searchEpisodesByTimeRangeStmt, err = db.PrepareContext(ctx, searchEpisodesByTimeRange); err != nil {
		return nil, fmt.Errorf("error preparing query SearchEpisodesByTimeRange: %w", err)
	}
	if q.searchEpisodesFullStmt, err = db.PrepareContext(ctx, searchEpisodesFull); err != nil {
		return nil, fmt.Errorf("error preparing query SearchEpisodesFull: %w", err)
	}
	if q.searchFactsStmt, err = db.PrepareContext(ctx, searchFacts); err != nil {
		return nil, fmt.Errorf("error preparing query SearchFacts: %w", err)
	}
	if q.searchProceduresStmt, err = db.PrepareContext(ctx, searchProcedures); err != nil {
		return nil, fmt.Errorf("error preparing query SearchProcedures: %w", err)
	}
	if q.updateAgencyStatusStmt, err = db.PrepareContext(ctx, updateAgencyStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAgencyStatus: %w", err)
	}
	if q.updateFactConfidenceStmt, err = db.PrepareContext(ctx, updateFactConfidence); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFactConfidence: %w", err)
	}
	if q.updateFileStmt, err = db.PrepareContext(ctx, updateFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFile: %w", err)
	}
	if q.updateGuardrailBudgetUsedStmt, err = db.PrepareContext(ctx, updateGuardrailBudgetUsed); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateGuardrailBudgetUsed: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateProcedureStatsStmt, err = db.PrepareContext(ctx, updateProcedureStats); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProcedureStats: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateTaskProgressStmt, err = db.PrepareContext(ctx, updateTaskProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTaskProgress: %w", err)
	}
	if q.updateTaskScheduleExprStmt, err = db.PrepareContext(ctx, updateTaskScheduleExpr); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTaskScheduleExpr: %w", err)
	}
	if q.updateTaskStatusStmt, err = db.PrepareContext(ctx, updateTaskStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTaskStatus: %w", err)
	}
	if q.upsertAgencyStateStmt, err = db.PrepareContext(ctx, upsertAgencyState); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAgencyState: %w", err)
	}
	if q.upsertGuardrailBudgetStmt, err = db.PrepareContext(ctx, upsertGuardrailBudget); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertGuardrailBudget: %w", err)
	}
	if q.upsertGuardrailPreferencesStmt, err = db.PrepareContext(ctx, upsertGuardrailPreferences); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertGuardrailPreferences: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addTaskDependencyStmt != nil {
		if cerr := q.addTaskDependencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTaskDependencyStmt: %w", cerr)
		}
	}
	if q.cancelTaskStmt != nil {
		if cerr := q.cancelTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelTaskStmt: %w", cerr)
		}
	}
	if q.countEpisodeEmbeddingsStmt != nil {
		if cerr := q.countEpisodeEmbeddingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countEpisodeEmbeddingsStmt: %w", cerr)
		}
	}
	if q.countEpisodesByOutcomeStmt != nil {
		if cerr := q.countEpisodesByOutcomeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countEpisodesByOutcomeStmt: %w", cerr)
		}
	}
	if q.countFactEmbeddingsStmt != nil {
		if cerr := q.countFactEmbeddingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countFactEmbeddingsStmt: %w", cerr)
		}
	}
	if q.countTasksByStatusStmt != nil {
		if cerr := q.countTasksByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTasksByStatusStmt: %w", cerr)
		}
	}
	if q.createAgencyStmt != nil {
		if cerr := q.createAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAgencyStmt: %w", cerr)
		}
	}
	if q.createEpisodeStmt != nil {
		if cerr := q.createEpisodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEpisodeStmt: %w", cerr)
		}
	}
	if q.createEpisodeEmbeddingStmt != nil {
		if cerr := q.createEpisodeEmbeddingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEpisodeEmbeddingStmt: %w", cerr)
		}
	}
	if q.createFactStmt != nil {
		if cerr := q.createFactStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFactStmt: %w", cerr)
		}
	}
	if q.createFactEmbeddingStmt != nil {
		if cerr := q.createFactEmbeddingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFactEmbeddingStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createGuardrailAuditEntryStmt != nil {
		if cerr := q.createGuardrailAuditEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGuardrailAuditEntryStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createPermissionRequestStmt != nil {
		if cerr := q.createPermissionRequestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPermissionRequestStmt: %w", cerr)
		}
	}
	if q.createPermissionResponseStmt != nil {
		if cerr := q.createPermissionResponseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPermissionResponseStmt: %w", cerr)
		}
	}
	if q.createPermissionRuleStmt != nil {
		if cerr := q.createPermissionRuleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPermissionRuleStmt: %w", cerr)
		}
	}
	if q.createProcedureStmt != nil {
		if cerr := q.createProcedureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProcedureStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createTaskStmt != nil {
		if cerr := q.createTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTaskStmt: %w", cerr)
		}
	}
	if q.createTaskEventStmt != nil {
		if cerr := q.createTaskEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTaskEventStmt: %w", cerr)
		}
	}
	if q.deleteAgencyStmt != nil {
		if cerr := q.deleteAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAgencyStmt: %w", cerr)
		}
	}
	if q.deleteAgencyStateStmt != nil {
		if cerr := q.deleteAgencyStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAgencyStateStmt: %w", cerr)
		}
	}
	if q.deleteEpisodeStmt != nil {
		if cerr := q.deleteEpisodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEpisodeStmt: %w", cerr)
		}
	}
	if q.deleteEpisodeEmbeddingStmt != nil {
		if cerr := q.deleteEpisodeEmbeddingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEpisodeEmbeddingStmt: %w", cerr)
		}
	}
	if q.deleteExpiredContextsStmt != nil {
		if cerr := q.deleteExpiredContextsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredContextsStmt: %w", cerr)
		}
	}
	if q.deleteExpiredPermissionRulesStmt != nil {
		if cerr := q.deleteExpiredPermissionRulesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredPermissionRulesStmt: %w", cerr)
		}
	}
	if q.deleteFactStmt != nil {
		if cerr := q.deleteFactStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFactStmt: %w", cerr)
		}
	}
	if q.deleteFactEmbeddingStmt != nil {
		if cerr := q.deleteFactEmbeddingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFactEmbeddingStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteOldEpisodesStmt != nil {
		if cerr := q.deleteOldEpisodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOldEpisodesStmt: %w", cerr)
		}
	}
	if q.deleteOldGuardrailAuditStmt != nil {
		if cerr := q.deleteOldGuardrailAuditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOldGuardrailAuditStmt: %w", cerr)
		}
	}
	if q.deleteOldPermissionRequestsStmt != nil {
		if cerr := q.deleteOldPermissionRequestsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOldPermissionRequestsStmt: %w", cerr)
		}
	}
	if q.deletePermissionRuleStmt != nil {
		if cerr := q.deletePermissionRuleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePermissionRuleStmt: %w", cerr)
		}
	}
	if q.deleteProcedureStmt != nil {
		if cerr := q.deleteProcedureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProcedureStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.deleteTaskStmt != nil {
		if cerr := q.deleteTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTaskStmt: %w", cerr)
		}
	}
	if q.deleteWorkingContextStmt != nil {
		if cerr := q.deleteWorkingContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteWorkingContextStmt: %w", cerr)
		}
	}
	if q.getAgencyByIDStmt != nil {
		if cerr := q.getAgencyByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgencyByIDStmt: %w", cerr)
		}
	}
	if q.getAgencyByNameStmt != nil {
		if cerr := q.getAgencyByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgencyByNameStmt: %w", cerr)
		}
	}
	if q.getAgencyStateStmt != nil {
		if cerr := q.getAgencyStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgencyStateStmt: %w", cerr)
		}
	}
	if q.getDependentTasksStmt != nil {
		if cerr := q.getDependentTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDependentTasksStmt: %w", cerr)
		}
	}
	if q.getEpisodeByIDStmt != nil {
		if cerr := q.getEpisodeByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEpisodeByIDStmt: %w", cerr)
		}
	}
	if q.getEpisodeEmbeddingStmt != nil {
		if cerr := q.getEpisodeEmbeddingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEpisodeEmbeddingStmt: %w", cerr)
		}
	}
	if q.getEpisodeEmbeddingByHashStmt != nil {
		if cerr := q.getEpisodeEmbeddingByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEpisodeEmbeddingByHashStmt: %w", cerr)
		}
	}
	if q.getFactByIDStmt != nil {
		if cerr := q.getFactByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFactByIDStmt: %w", cerr)
		}
	}
	if q.getFactEmbeddingStmt != nil {
		if cerr := q.getFactEmbeddingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFactEmbeddingStmt: %w", cerr)
		}
	}
	if q.getFactEmbeddingByHashStmt != nil {
		if cerr := q.getFactEmbeddingByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFactEmbeddingByHashStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getGuardrailBudgetStmt != nil {
		if cerr := q.getGuardrailBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGuardrailBudgetStmt: %w", cerr)
		}
	}
	if q.getGuardrailPreferencesStmt != nil {
		if cerr := q.getGuardrailPreferencesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGuardrailPreferencesStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getPermissionRequestByIDStmt != nil {
		if cerr := q.getPermissionRequestByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPermissionRequestByIDStmt: %w", cerr)
		}
	}
	if q.getPermissionResponseByRequestIDStmt != nil {
		if cerr := q.getPermissionResponseByRequestIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPermissionResponseByRequestIDStmt: %w", cerr)
		}
	}
	if q.getPermissionRuleByIDStmt != nil {
		if cerr := q.getPermissionRuleByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPermissionRuleByIDStmt: %w", cerr)
		}
	}
	if q.getProcedureByIDStmt != nil {
		if cerr := q.getProcedureByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProcedureByIDStmt: %w", cerr)
		}
	}
	if q.getProcedureByNameStmt != nil {
		if cerr := q.getProcedureByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProcedureByNameStmt: %w", cerr)
		}
	}
	if q.getRecentTaskEventsStmt != nil {
		if cerr := q.getRecentTaskEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentTaskEventsStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getTaskByIDStmt != nil {
		if cerr := q.getTaskByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskByIDStmt: %w", cerr)
		}
	}
	if q.getTaskDependenciesStmt != nil {
		if cerr := q.getTaskDependenciesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskDependenciesStmt: %w", cerr)
		}
	}
	if q.getTaskEventsStmt != nil {
		if cerr := q.getTaskEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskEventsStmt: %w", cerr)
		}
	}
	if q.getWorkingContextStmt != nil {
		if cerr := q.getWorkingContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorkingContextStmt: %w", cerr)
		}
	}
	if q.incrementFactUsageStmt != nil {
		if cerr := q.incrementFactUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementFactUsageStmt: %w", cerr)
		}
	}
	if q.listAgenciesStmt != nil {
		if cerr := q.listAgenciesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgenciesStmt: %w", cerr)
		}
	}
	if q.listAgenciesByStatusStmt != nil {
		if cerr := q.listAgenciesByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgenciesByStatusStmt: %w", cerr)
		}
	}
	if q.listEpisodeEmbeddingsStmt != nil {
		if cerr := q.listEpisodeEmbeddingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEpisodeEmbeddingsStmt: %w", cerr)
		}
	}
	if q.listEpisodesStmt != nil {
		if cerr := q.listEpisodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEpisodesStmt: %w", cerr)
		}
	}
	if q.listEpisodesByAgencyStmt != nil {
		if cerr := q.listEpisodesByAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEpisodesByAgencyStmt: %w", cerr)
		}
	}
	if q.listEpisodesBySessionStmt != nil {
		if cerr := q.listEpisodesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEpisodesBySessionStmt: %w", cerr)
		}
	}
	if q.listFactEmbeddingsStmt != nil {
		if cerr := q.listFactEmbeddingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFactEmbeddingsStmt: %w", cerr)
		}
	}
	if q.listFactsByCategoryStmt != nil {
		if cerr := q.listFactsByCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFactsByCategoryStmt: %w", cerr)
		}
	}
	if q.listFactsByDomainStmt != nil {
		if cerr := q.listFactsByDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFactsByDomainStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listGuardrailAuditByTimeRangeStmt != nil {
		if cerr := q.listGuardrailAuditByTimeRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGuardrailAuditByTimeRangeStmt: %w", cerr)
		}
	}
	if q.listGuardrailAuditByTypeStmt != nil {
		if cerr := q.listGuardrailAuditByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGuardrailAuditByTypeStmt: %w", cerr)
		}
	}
	if q.listGuardrailBudgetsStmt != nil {
		if cerr := q.listGuardrailBudgetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGuardrailBudgetsStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listPendingTasksStmt != nil {
		if cerr := q.listPendingTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingTasksStmt: %w", cerr)
		}
	}
	if q.listPermissionRequestsByAgencyStmt != nil {
		if cerr := q.listPermissionRequestsByAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPermissionRequestsByAgencyStmt: %w", cerr)
		}
	}
	if q.listPermissionRequestsByAgentStmt != nil {
		if cerr := q.listPermissionRequestsByAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPermissionRequestsByAgentStmt: %w", cerr)
		}
	}
	if q.listPermissionRulesByAgencyStmt != nil {
		if cerr := q.listPermissionRulesByAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPermissionRulesByAgencyStmt: %w", cerr)
		}
	}
	if q.listProceduresStmt != nil {
		if cerr := q.listProceduresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProceduresStmt: %w", cerr)
		}
	}
	if q.listProceduresByTriggerStmt != nil {
		if cerr := q.listProceduresByTriggerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProceduresByTriggerStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listTasksStmt != nil {
		if cerr := q.listTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksStmt: %w", cerr)
		}
	}
	if q.listTasksByAgencyStmt != nil {
		if cerr := q.listTasksByAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksByAgencyStmt: %w", cerr)
		}
	}
	if q.listTasksByStatusStmt != nil {
		if cerr := q.listTasksByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksByStatusStmt: %w", cerr)
		}
	}
	if q.removeTaskDependencyStmt != nil {
		if cerr := q.removeTaskDependencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeTaskDependencyStmt: %w", cerr)
		}
	}
	if q.resetGuardrailBudgetsStmt != nil {
		if cerr := q.resetGuardrailBudgetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetGuardrailBudgetsStmt: %w", cerr)
		}
	}
	if q.saveWorkingContextStmt != nil {
		if cerr := q.saveWorkingContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveWorkingContextStmt: %w", cerr)
		}
	}
	if q.searchEpisodesStmt != nil {
		if cerr := q.searchEpisodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchEpisodesStmt: %w", cerr)
		}
	}
	if q.searchEpisodesByAgentStmt != nil {
		if cerr := q.searchEpisodesByAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchEpisodesByAgentStmt: %w", cerr)
		}
	}
	if q.searchEpisodesByTimeRangeStmt != nil {
		if cerr := q.searchEpisodesByTimeRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchEpisodesByTimeRangeStmt: %w", cerr)
		}
	}
	if q.searchEpisodesFullStmt != nil {
		if cerr := q.searchEpisodesFullStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchEpisodesFullStmt: %w", cerr)
		}
	}
	if q.searchFactsStmt != nil {
		if cerr := q.searchFactsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchFactsStmt: %w", cerr)
		}
	}
	if q.searchProceduresStmt != nil {
		if cerr := q.searchProceduresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchProceduresStmt: %w", cerr)
		}
	}
	if q.updateAgencyStatusStmt != nil {
		if cerr := q.updateAgencyStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAgencyStatusStmt: %w", cerr)
		}
	}
	if q.updateFactConfidenceStmt != nil {
		if cerr := q.updateFactConfidenceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFactConfidenceStmt: %w", cerr)
		}
	}
	if q.updateFileStmt != nil {
		if cerr := q.updateFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFileStmt: %w", cerr)
		}
	}
	if q.updateGuardrailBudgetUsedStmt != nil {
		if cerr := q.updateGuardrailBudgetUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateGuardrailBudgetUsedStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateProcedureStatsStmt != nil {
		if cerr := q.updateProcedureStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProcedureStatsStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateTaskProgressStmt != nil {
		if cerr := q.updateTaskProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTaskProgressStmt: %w", cerr)
		}
	}
	if q.updateTaskScheduleExprStmt != nil {
		if cerr := q.updateTaskScheduleExprStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTaskScheduleExprStmt: %w", cerr)
		}
	}
	if q.updateTaskStatusStmt != nil {
		if cerr := q.updateTaskStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTaskStatusStmt: %w", cerr)
		}
	}
	if q.upsertAgencyStateStmt != nil {
		if cerr := q.upsertAgencyStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAgencyStateStmt: %w", cerr)
		}
	}
	if q.upsertGuardrailBudgetStmt != nil {
		if cerr := q.upsertGuardrailBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertGuardrailBudgetStmt: %w", cerr)
		}
	}
	if q.upsertGuardrailPreferencesStmt != nil {
		if cerr := q.upsertGuardrailPreferencesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertGuardrailPreferencesStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	addTaskDependencyStmt                *sql.Stmt
	cancelTaskStmt                       *sql.Stmt
	countEpisodeEmbeddingsStmt           *sql.Stmt
	countEpisodesByOutcomeStmt           *sql.Stmt
	countFactEmbeddingsStmt              *sql.Stmt
	countTasksByStatusStmt               *sql.Stmt
	createAgencyStmt                     *sql.Stmt
	createEpisodeStmt                    *sql.Stmt
	createEpisodeEmbeddingStmt           *sql.Stmt
	createFactStmt                       *sql.Stmt
	createFactEmbeddingStmt              *sql.Stmt
	createFileStmt                       *sql.Stmt
	createGuardrailAuditEntryStmt        *sql.Stmt
	createMessageStmt                    *sql.Stmt
	createPermissionRequestStmt          *sql.Stmt
	createPermissionResponseStmt         *sql.Stmt
	createPermissionRuleStmt             *sql.Stmt
	createProcedureStmt                  *sql.Stmt
	createSessionStmt                    *sql.Stmt
	createTaskStmt                       *sql.Stmt
	createTaskEventStmt                  *sql.Stmt
	deleteAgencyStmt                     *sql.Stmt
	deleteAgencyStateStmt                *sql.Stmt
	deleteEpisodeStmt                    *sql.Stmt
	deleteEpisodeEmbeddingStmt           *sql.Stmt
	deleteExpiredContextsStmt            *sql.Stmt
	deleteExpiredPermissionRulesStmt     *sql.Stmt
	deleteFactStmt                       *sql.Stmt
	deleteFactEmbeddingStmt              *sql.Stmt
	deleteFileStmt                       *sql.Stmt
	deleteMessageStmt                    *sql.Stmt
	deleteOldEpisodesStmt                *sql.Stmt
	deleteOldGuardrailAuditStmt          *sql.Stmt
	deleteOldPermissionRequestsStmt      *sql.Stmt
	deletePermissionRuleStmt             *sql.Stmt
	deleteProcedureStmt                  *sql.Stmt
	deleteSessionStmt                    *sql.Stmt
	deleteSessionFilesStmt               *sql.Stmt
	deleteSessionMessagesStmt            *sql.Stmt
	deleteTaskStmt                       *sql.Stmt
	deleteWorkingContextStmt             *sql.Stmt
	getAgencyByIDStmt                    *sql.Stmt
	getAgencyByNameStmt                  *sql.Stmt
	getAgencyStateStmt                   *sql.Stmt
	getDependentTasksStmt                *sql.Stmt
	getEpisodeByIDStmt                   *sql.Stmt
	getEpisodeEmbeddingStmt              *sql.Stmt
	getEpisodeEmbeddingByHashStmt        *sql.Stmt
	getFactByIDStmt                      *sql.Stmt
	getFactEmbeddingStmt                 *sql.Stmt
	getFactEmbeddingByHashStmt           *sql.Stmt
	getFileStmt                          *sql.Stmt
	getFileByPathAndSessionStmt          *sql.Stmt
	getGuardrailBudgetStmt               *sql.Stmt
	getGuardrailPreferencesStmt          *sql.Stmt
	getMessageStmt                       *sql.Stmt
	getPermissionRequestByIDStmt         *sql.Stmt
	getPermissionResponseByRequestIDStmt *sql.Stmt
	getPermissionRuleByIDStmt            *sql.Stmt
	getProcedureByIDStmt                 *sql.Stmt
	getProcedureByNameStmt               *sql.Stmt
	getRecentTaskEventsStmt              *sql.Stmt
	getSessionByIDStmt                   *sql.Stmt
	getTaskByIDStmt                      *sql.Stmt
	getTaskDependenciesStmt              *sql.Stmt
	getTaskEventsStmt                    *sql.Stmt
	getWorkingContextStmt                *sql.Stmt
	incrementFactUsageStmt               *sql.Stmt
	listAgenciesStmt                     *sql.Stmt
	listAgenciesByStatusStmt             *sql.Stmt
	listEpisodeEmbeddingsStmt            *sql.Stmt
	listEpisodesStmt                     *sql.Stmt
	listEpisodesByAgencyStmt             *sql.Stmt
	listEpisodesBySessionStmt            *sql.Stmt
	listFactEmbeddingsStmt               *sql.Stmt
	listFactsByCategoryStmt              *sql.Stmt
	listFactsByDomainStmt                *sql.Stmt
	listFilesByPathStmt                  *sql.Stmt
	listFilesBySessionStmt               *sql.Stmt
	listGuardrailAuditByTimeRangeStmt    *sql.Stmt
	listGuardrailAuditByTypeStmt         *sql.Stmt
	listGuardrailBudgetsStmt             *sql.Stmt
	listLatestSessionFilesStmt           *sql.Stmt
	listMessagesBySessionStmt            *sql.Stmt
	listNewFilesStmt                     *sql.Stmt
	listPendingTasksStmt                 *sql.Stmt
	listPermissionRequestsByAgencyStmt   *sql.Stmt
	listPermissionRequestsByAgentStmt    *sql.Stmt
	listPermissionRulesByAgencyStmt      *sql.Stmt
	listProceduresStmt                   *sql.Stmt
	listProceduresByTriggerStmt          *sql.Stmt
	listSessionsStmt                     *sql.Stmt
	listTasksStmt                        *sql.Stmt
	listTasksByAgencyStmt                *sql.Stmt
	listTasksByStatusStmt                *sql.Stmt
	removeTaskDependencyStmt             *sql.Stmt
	resetGuardrailBudgetsStmt            *sql.Stmt
	saveWorkingContextStmt               *sql.Stmt
	searchEpisodesStmt                   *sql.Stmt
	searchEpisodesByAgentStmt            *sql.Stmt
	searchEpisodesByTimeRangeStmt        *sql.Stmt
	searchEpisodesFullStmt               *sql.Stmt
	searchFactsStmt                      *sql.Stmt
	searchProceduresStmt                 *sql.Stmt
	updateAgencyStatusStmt               *sql.Stmt
	updateFactConfidenceStmt             *sql.Stmt
	updateFileStmt                       *sql.Stmt
	updateGuardrailBudgetUsedStmt        *sql.Stmt
	updateMessageStmt                    *sql.Stmt
	updateProcedureStatsStmt             *sql.Stmt
	updateSessionStmt                    *sql.Stmt
	updateTaskProgressStmt               *sql.Stmt
	updateTaskScheduleExprStmt           *sql.Stmt
	updateTaskStatusStmt                 *sql.Stmt
	upsertAgencyStateStmt                *sql.Stmt
	upsertGuardrailBudgetStmt            *sql.Stmt
	upsertGuardrailPreferencesStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		addTaskDependencyStmt:                q.addTaskDependencyStmt,
		cancelTaskStmt:                       q.cancelTaskStmt,
		countEpisodeEmbeddingsStmt:           q.countEpisodeEmbeddingsStmt,
		countEpisodesByOutcomeStmt:           q.countEpisodesByOutcomeStmt,
		countFactEmbeddingsStmt:              q.countFactEmbeddingsStmt,
		countTasksByStatusStmt:               q.countTasksByStatusStmt,
		createAgencyStmt:                     q.createAgencyStmt,
		createEpisodeStmt:                    q.createEpisodeStmt,
		createEpisodeEmbeddingStmt:           q.createEpisodeEmbeddingStmt,
		createFactStmt:                       q.createFactStmt,
		createFactEmbeddingStmt:              q.createFactEmbeddingStmt,
		createFileStmt:                       q.createFileStmt,
		createGuardrailAuditEntryStmt:        q.createGuardrailAuditEntryStmt,
		createMessageStmt:                    q.createMessageStmt,
		createPermissionRequestStmt:          q.createPermissionRequestStmt,
		createPermissionResponseStmt:         q.createPermissionResponseStmt,
		createPermissionRuleStmt:             q.createPermissionRuleStmt,
		createProcedureStmt:                  q.createProcedureStmt,
		createSessionStmt:                    q.createSessionStmt,
		createTaskStmt:                       q.createTaskStmt,
		createTaskEventStmt:                  q.createTaskEventStmt,
		deleteAgencyStmt:                     q.deleteAgencyStmt,
		deleteAgencyStateStmt:                q.deleteAgencyStateStmt,
		deleteEpisodeStmt:                    q.deleteEpisodeStmt,
		deleteEpisodeEmbeddingStmt:           q.deleteEpisodeEmbeddingStmt,
		deleteExpiredContextsStmt:            q.deleteExpiredContextsStmt,
		deleteExpiredPermissionRulesStmt:     q.deleteExpiredPermissionRulesStmt,
		deleteFactStmt:                       q.deleteFactStmt,
		deleteFactEmbeddingStmt:              q.deleteFactEmbeddingStmt,
		deleteFileStmt:                       q.deleteFileStmt,
		deleteMessageStmt:                    q.deleteMessageStmt,
		deleteOldEpisodesStmt:                q.deleteOldEpisodesStmt,
		deleteOldGuardrailAuditStmt:          q.deleteOldGuardrailAuditStmt,
		deleteOldPermissionRequestsStmt:      q.deleteOldPermissionRequestsStmt,
		deletePermissionRuleStmt:             q.deletePermissionRuleStmt,
		deleteProcedureStmt:                  q.deleteProcedureStmt,
		deleteSessionStmt:                    q.deleteSessionStmt,
		deleteSessionFilesStmt:               q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:            q.deleteSessionMessagesStmt,
		deleteTaskStmt:                       q.deleteTaskStmt,
		deleteWorkingContextStmt:             q.deleteWorkingContextStmt,
		getAgencyByIDStmt:                    q.getAgencyByIDStmt,
		getAgencyByNameStmt:                  q.getAgencyByNameStmt,
		getAgencyStateStmt:                   q.getAgencyStateStmt,
		getDependentTasksStmt:                q.getDependentTasksStmt,
		getEpisodeByIDStmt:                   q.getEpisodeByIDStmt,
		getEpisodeEmbeddingStmt:              q.getEpisodeEmbeddingStmt,
		getEpisodeEmbeddingByHashStmt:        q.getEpisodeEmbeddingByHashStmt,
		getFactByIDStmt:                      q.getFactByIDStmt,
		getFactEmbeddingStmt:                 q.getFactEmbeddingStmt,
		getFactEmbeddingByHashStmt:           q.getFactEmbeddingByHashStmt,
		getFileStmt:                          q.getFileStmt,
		getFileByPathAndSessionStmt:          q.getFileByPathAndSessionStmt,
		getGuardrailBudgetStmt:               q.getGuardrailBudgetStmt,
		getGuardrailPreferencesStmt:          q.getGuardrailPreferencesStmt,
		getMessageStmt:                       q.getMessageStmt,
		getPermissionRequestByIDStmt:         q.getPermissionRequestByIDStmt,
		getPermissionResponseByRequestIDStmt: q.getPermissionResponseByRequestIDStmt,
		getPermissionRuleByIDStmt:            q.getPermissionRuleByIDStmt,
		getProcedureByIDStmt:                 q.getProcedureByIDStmt,
		getProcedureByNameStmt:               q.getProcedureByNameStmt,
		getRecentTaskEventsStmt:              q.getRecentTaskEventsStmt,
		getSessionByIDStmt:                   q.getSessionByIDStmt,
		getTaskByIDStmt:                      q.getTaskByIDStmt,
		getTaskDependenciesStmt:              q.getTaskDependenciesStmt,
		getTaskEventsStmt:                    q.getTaskEventsStmt,
		getWorkingContextStmt:                q.getWorkingContextStmt,
		incrementFactUsageStmt:               q.incrementFactUsageStmt,
		listAgenciesStmt:                     q.listAgenciesStmt,
		listAgenciesByStatusStmt:             q.listAgenciesByStatusStmt,
		listEpisodeEmbeddingsStmt:            q.listEpisodeEmbeddingsStmt,
		listEpisodesStmt:                     q.listEpisodesStmt,
		listEpisodesByAgencyStmt:             q.listEpisodesByAgencyStmt,
		listEpisodesBySessionStmt:            q.listEpisodesBySessionStmt,
		listFactEmbeddingsStmt:               q.listFactEmbeddingsStmt,
		listFactsByCategoryStmt:              q.listFactsByCategoryStmt,
		listFactsByDomainStmt:                q.listFactsByDomainStmt,
		listFilesByPathStmt:                  q.listFilesByPathStmt,
		listFilesBySessionStmt:               q.listFilesBySessionStmt,
		listGuardrailAuditByTimeRangeStmt:    q.listGuardrailAuditByTimeRangeStmt,
		listGuardrailAuditByTypeStmt:         q.listGuardrailAuditByTypeStmt,
		listGuardrailBudgetsStmt:             q.listGuardrailBudgetsStmt,
		listLatestSessionFilesStmt:           q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:            q.listMessagesBySessionStmt,
		listNewFilesStmt:                     q.listNewFilesStmt,
		listPendingTasksStmt:                 q.listPendingTasksStmt,
		listPermissionRequestsByAgencyStmt:   q.listPermissionRequestsByAgencyStmt,
		listPermissionRequestsByAgentStmt:    q.listPermissionRequestsByAgentStmt,
		listPermissionRulesByAgencyStmt:      q.listPermissionRulesByAgencyStmt,
		listProceduresStmt:                   q.listProceduresStmt,
		listProceduresByTriggerStmt:          q.listProceduresByTriggerStmt,
		listSessionsStmt:                     q.listSessionsStmt,
		listTasksStmt:                        q.listTasksStmt,
		listTasksByAgencyStmt:                q.listTasksByAgencyStmt,
		listTasksByStatusStmt:                q.listTasksByStatusStmt,
		removeTaskDependencyStmt:             q.removeTaskDependencyStmt,
		resetGuardrailBudgetsStmt:            q.resetGuardrailBudgetsStmt,
		saveWorkingContextStmt:               q.saveWorkingContextStmt,
		searchEpisodesStmt:                   q.searchEpisodesStmt,
		searchEpisodesByAgentStmt:            q.searchEpisodesByAgentStmt,
		searchEpisodesByTimeRangeStmt:        q.searchEpisodesByTimeRangeStmt,
		searchEpisodesFullStmt:               q.searchEpisodesFullStmt,
		searchFactsStmt:                      q.searchFactsStmt,
		searchProceduresStmt:                 q.searchProceduresStmt,
		updateAgencyStatusStmt:               q.updateAgencyStatusStmt,
		updateFactConfidenceStmt:             q.updateFactConfidenceStmt,
		updateFileStmt:                       q.updateFileStmt,
		updateGuardrailBudgetUsedStmt:        q.updateGuardrailBudgetUsedStmt,
		updateMessageStmt:                    q.updateMessageStmt,
		updateProcedureStatsStmt:             q.updateProcedureStatsStmt,
		updateSessionStmt:                    q.updateSessionStmt,
		updateTaskProgressStmt:               q.updateTaskProgressStmt,
		updateTaskScheduleExprStmt:           q.updateTaskScheduleExprStmt,
		updateTaskStatusStmt:                 q.updateTaskStatusStmt,
		upsertAgencyStateStmt:                q.upsertAgencyStateStmt,
		upsertGuardrailBudgetStmt:            q.upsertGuardrailBudgetStmt,
		upsertGuardrailPreferencesStmt:       q.upsertGuardrailPreferencesStmt,
	}
}
