// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addTaskDependencyStmt, err = db.PrepareContext(ctx, addTaskDependency); err != nil {
		return nil, fmt.Errorf("error preparing query AddTaskDependency: %w", err)
	}
	if q.cancelTaskStmt, err = db.PrepareContext(ctx, cancelTask); err != nil {
		return nil, fmt.Errorf("error preparing query CancelTask: %w", err)
	}
	if q.createAgencyStmt, err = db.PrepareContext(ctx, createAgency); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAgency: %w", err)
	}
	if q.createEpisodeStmt, err = db.PrepareContext(ctx, createEpisode); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEpisode: %w", err)
	}
	if q.createFactStmt, err = db.PrepareContext(ctx, createFact); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFact: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createProcedureStmt, err = db.PrepareContext(ctx, createProcedure); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProcedure: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createTaskStmt, err = db.PrepareContext(ctx, createTask); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTask: %w", err)
	}
	if q.createTaskEventStmt, err = db.PrepareContext(ctx, createTaskEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTaskEvent: %w", err)
	}
	if q.deleteAgencyStmt, err = db.PrepareContext(ctx, deleteAgency); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAgency: %w", err)
	}
	if q.deleteEpisodeStmt, err = db.PrepareContext(ctx, deleteEpisode); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEpisode: %w", err)
	}
	if q.deleteFactStmt, err = db.PrepareContext(ctx, deleteFact); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFact: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteOldEpisodesStmt, err = db.PrepareContext(ctx, deleteOldEpisodes); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOldEpisodes: %w", err)
	}
	if q.deleteProcedureStmt, err = db.PrepareContext(ctx, deleteProcedure); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProcedure: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.deleteTaskStmt, err = db.PrepareContext(ctx, deleteTask); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTask: %w", err)
	}
	if q.getAgencyByIDStmt, err = db.PrepareContext(ctx, getAgencyByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgencyByID: %w", err)
	}
	if q.getAgencyByNameStmt, err = db.PrepareContext(ctx, getAgencyByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgencyByName: %w", err)
	}
	if q.getDependentTasksStmt, err = db.PrepareContext(ctx, getDependentTasks); err != nil {
		return nil, fmt.Errorf("error preparing query GetDependentTasks: %w", err)
	}
	if q.getEpisodeByIDStmt, err = db.PrepareContext(ctx, getEpisodeByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetEpisodeByID: %w", err)
	}
	if q.getFactByIDStmt, err = db.PrepareContext(ctx, getFactByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFactByID: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getProcedureByIDStmt, err = db.PrepareContext(ctx, getProcedureByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProcedureByID: %w", err)
	}
	if q.getProcedureByNameStmt, err = db.PrepareContext(ctx, getProcedureByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetProcedureByName: %w", err)
	}
	if q.getRecentTaskEventsStmt, err = db.PrepareContext(ctx, getRecentTaskEvents); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentTaskEvents: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getTaskByIDStmt, err = db.PrepareContext(ctx, getTaskByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTaskByID: %w", err)
	}
	if q.getTaskDependenciesStmt, err = db.PrepareContext(ctx, getTaskDependencies); err != nil {
		return nil, fmt.Errorf("error preparing query GetTaskDependencies: %w", err)
	}
	if q.getTaskEventsStmt, err = db.PrepareContext(ctx, getTaskEvents); err != nil {
		return nil, fmt.Errorf("error preparing query GetTaskEvents: %w", err)
	}
	if q.incrementFactUsageStmt, err = db.PrepareContext(ctx, incrementFactUsage); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementFactUsage: %w", err)
	}
	if q.listAgenciesStmt, err = db.PrepareContext(ctx, listAgencies); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgencies: %w", err)
	}
	if q.listAgenciesByStatusStmt, err = db.PrepareContext(ctx, listAgenciesByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgenciesByStatus: %w", err)
	}
	if q.listEpisodesStmt, err = db.PrepareContext(ctx, listEpisodes); err != nil {
		return nil, fmt.Errorf("error preparing query ListEpisodes: %w", err)
	}
	if q.listEpisodesByAgencyStmt, err = db.PrepareContext(ctx, listEpisodesByAgency); err != nil {
		return nil, fmt.Errorf("error preparing query ListEpisodesByAgency: %w", err)
	}
	if q.listEpisodesBySessionStmt, err = db.PrepareContext(ctx, listEpisodesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListEpisodesBySession: %w", err)
	}
	if q.listFactsByCategoryStmt, err = db.PrepareContext(ctx, listFactsByCategory); err != nil {
		return nil, fmt.Errorf("error preparing query ListFactsByCategory: %w", err)
	}
	if q.listFactsByDomainStmt, err = db.PrepareContext(ctx, listFactsByDomain); err != nil {
		return nil, fmt.Errorf("error preparing query ListFactsByDomain: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listProceduresStmt, err = db.PrepareContext(ctx, listProcedures); err != nil {
		return nil, fmt.Errorf("error preparing query ListProcedures: %w", err)
	}
	if q.listProceduresByTriggerStmt, err = db.PrepareContext(ctx, listProceduresByTrigger); err != nil {
		return nil, fmt.Errorf("error preparing query ListProceduresByTrigger: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listTasksStmt, err = db.PrepareContext(ctx, listTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasks: %w", err)
	}
	if q.listTasksByAgencyStmt, err = db.PrepareContext(ctx, listTasksByAgency); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasksByAgency: %w", err)
	}
	if q.listTasksByStatusStmt, err = db.PrepareContext(ctx, listTasksByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasksByStatus: %w", err)
	}
	if q.removeTaskDependencyStmt, err = db.PrepareContext(ctx, removeTaskDependency); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveTaskDependency: %w", err)
	}
	if q.searchEpisodesStmt, err = db.PrepareContext(ctx, searchEpisodes); err != nil {
		return nil, fmt.Errorf("error preparing query SearchEpisodes: %w", err)
	}
	if q.searchFactsStmt, err = db.PrepareContext(ctx, searchFacts); err != nil {
		return nil, fmt.Errorf("error preparing query SearchFacts: %w", err)
	}
	if q.searchProceduresStmt, err = db.PrepareContext(ctx, searchProcedures); err != nil {
		return nil, fmt.Errorf("error preparing query SearchProcedures: %w", err)
	}
	if q.updateAgencyStatusStmt, err = db.PrepareContext(ctx, updateAgencyStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAgencyStatus: %w", err)
	}
	if q.updateFactConfidenceStmt, err = db.PrepareContext(ctx, updateFactConfidence); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFactConfidence: %w", err)
	}
	if q.updateFileStmt, err = db.PrepareContext(ctx, updateFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFile: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateProcedureStatsStmt, err = db.PrepareContext(ctx, updateProcedureStats); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProcedureStats: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateTaskProgressStmt, err = db.PrepareContext(ctx, updateTaskProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTaskProgress: %w", err)
	}
	if q.updateTaskStatusStmt, err = db.PrepareContext(ctx, updateTaskStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTaskStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addTaskDependencyStmt != nil {
		if cerr := q.addTaskDependencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTaskDependencyStmt: %w", cerr)
		}
	}
	if q.cancelTaskStmt != nil {
		if cerr := q.cancelTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelTaskStmt: %w", cerr)
		}
	}
	if q.createAgencyStmt != nil {
		if cerr := q.createAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAgencyStmt: %w", cerr)
		}
	}
	if q.createEpisodeStmt != nil {
		if cerr := q.createEpisodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEpisodeStmt: %w", cerr)
		}
	}
	if q.createFactStmt != nil {
		if cerr := q.createFactStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFactStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createProcedureStmt != nil {
		if cerr := q.createProcedureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProcedureStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createTaskStmt != nil {
		if cerr := q.createTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTaskStmt: %w", cerr)
		}
	}
	if q.createTaskEventStmt != nil {
		if cerr := q.createTaskEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTaskEventStmt: %w", cerr)
		}
	}
	if q.deleteAgencyStmt != nil {
		if cerr := q.deleteAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAgencyStmt: %w", cerr)
		}
	}
	if q.deleteEpisodeStmt != nil {
		if cerr := q.deleteEpisodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEpisodeStmt: %w", cerr)
		}
	}
	if q.deleteFactStmt != nil {
		if cerr := q.deleteFactStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFactStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteOldEpisodesStmt != nil {
		if cerr := q.deleteOldEpisodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOldEpisodesStmt: %w", cerr)
		}
	}
	if q.deleteProcedureStmt != nil {
		if cerr := q.deleteProcedureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProcedureStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.deleteTaskStmt != nil {
		if cerr := q.deleteTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTaskStmt: %w", cerr)
		}
	}
	if q.getAgencyByIDStmt != nil {
		if cerr := q.getAgencyByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgencyByIDStmt: %w", cerr)
		}
	}
	if q.getAgencyByNameStmt != nil {
		if cerr := q.getAgencyByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgencyByNameStmt: %w", cerr)
		}
	}
	if q.getDependentTasksStmt != nil {
		if cerr := q.getDependentTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDependentTasksStmt: %w", cerr)
		}
	}
	if q.getEpisodeByIDStmt != nil {
		if cerr := q.getEpisodeByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEpisodeByIDStmt: %w", cerr)
		}
	}
	if q.getFactByIDStmt != nil {
		if cerr := q.getFactByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFactByIDStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getProcedureByIDStmt != nil {
		if cerr := q.getProcedureByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProcedureByIDStmt: %w", cerr)
		}
	}
	if q.getProcedureByNameStmt != nil {
		if cerr := q.getProcedureByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProcedureByNameStmt: %w", cerr)
		}
	}
	if q.getRecentTaskEventsStmt != nil {
		if cerr := q.getRecentTaskEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentTaskEventsStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getTaskByIDStmt != nil {
		if cerr := q.getTaskByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskByIDStmt: %w", cerr)
		}
	}
	if q.getTaskDependenciesStmt != nil {
		if cerr := q.getTaskDependenciesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskDependenciesStmt: %w", cerr)
		}
	}
	if q.getTaskEventsStmt != nil {
		if cerr := q.getTaskEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskEventsStmt: %w", cerr)
		}
	}
	if q.incrementFactUsageStmt != nil {
		if cerr := q.incrementFactUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementFactUsageStmt: %w", cerr)
		}
	}
	if q.listAgenciesStmt != nil {
		if cerr := q.listAgenciesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgenciesStmt: %w", cerr)
		}
	}
	if q.listAgenciesByStatusStmt != nil {
		if cerr := q.listAgenciesByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgenciesByStatusStmt: %w", cerr)
		}
	}
	if q.listEpisodesStmt != nil {
		if cerr := q.listEpisodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEpisodesStmt: %w", cerr)
		}
	}
	if q.listEpisodesByAgencyStmt != nil {
		if cerr := q.listEpisodesByAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEpisodesByAgencyStmt: %w", cerr)
		}
	}
	if q.listEpisodesBySessionStmt != nil {
		if cerr := q.listEpisodesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEpisodesBySessionStmt: %w", cerr)
		}
	}
	if q.listFactsByCategoryStmt != nil {
		if cerr := q.listFactsByCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFactsByCategoryStmt: %w", cerr)
		}
	}
	if q.listFactsByDomainStmt != nil {
		if cerr := q.listFactsByDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFactsByDomainStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listProceduresStmt != nil {
		if cerr := q.listProceduresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProceduresStmt: %w", cerr)
		}
	}
	if q.listProceduresByTriggerStmt != nil {
		if cerr := q.listProceduresByTriggerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProceduresByTriggerStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listTasksStmt != nil {
		if cerr := q.listTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksStmt: %w", cerr)
		}
	}
	if q.listTasksByAgencyStmt != nil {
		if cerr := q.listTasksByAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksByAgencyStmt: %w", cerr)
		}
	}
	if q.listTasksByStatusStmt != nil {
		if cerr := q.listTasksByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksByStatusStmt: %w", cerr)
		}
	}
	if q.removeTaskDependencyStmt != nil {
		if cerr := q.removeTaskDependencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeTaskDependencyStmt: %w", cerr)
		}
	}
	if q.searchEpisodesStmt != nil {
		if cerr := q.searchEpisodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchEpisodesStmt: %w", cerr)
		}
	}
	if q.searchFactsStmt != nil {
		if cerr := q.searchFactsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchFactsStmt: %w", cerr)
		}
	}
	if q.searchProceduresStmt != nil {
		if cerr := q.searchProceduresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchProceduresStmt: %w", cerr)
		}
	}
	if q.updateAgencyStatusStmt != nil {
		if cerr := q.updateAgencyStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAgencyStatusStmt: %w", cerr)
		}
	}
	if q.updateFactConfidenceStmt != nil {
		if cerr := q.updateFactConfidenceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFactConfidenceStmt: %w", cerr)
		}
	}
	if q.updateFileStmt != nil {
		if cerr := q.updateFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFileStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateProcedureStatsStmt != nil {
		if cerr := q.updateProcedureStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProcedureStatsStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateTaskProgressStmt != nil {
		if cerr := q.updateTaskProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTaskProgressStmt: %w", cerr)
		}
	}
	if q.updateTaskStatusStmt != nil {
		if cerr := q.updateTaskStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTaskStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	addTaskDependencyStmt       *sql.Stmt
	cancelTaskStmt              *sql.Stmt
	createAgencyStmt            *sql.Stmt
	createEpisodeStmt           *sql.Stmt
	createFactStmt              *sql.Stmt
	createFileStmt              *sql.Stmt
	createMessageStmt           *sql.Stmt
	createProcedureStmt         *sql.Stmt
	createSessionStmt           *sql.Stmt
	createTaskStmt              *sql.Stmt
	createTaskEventStmt         *sql.Stmt
	deleteAgencyStmt            *sql.Stmt
	deleteEpisodeStmt           *sql.Stmt
	deleteFactStmt              *sql.Stmt
	deleteFileStmt              *sql.Stmt
	deleteMessageStmt           *sql.Stmt
	deleteOldEpisodesStmt       *sql.Stmt
	deleteProcedureStmt         *sql.Stmt
	deleteSessionStmt           *sql.Stmt
	deleteSessionFilesStmt      *sql.Stmt
	deleteSessionMessagesStmt   *sql.Stmt
	deleteTaskStmt              *sql.Stmt
	getAgencyByIDStmt           *sql.Stmt
	getAgencyByNameStmt         *sql.Stmt
	getDependentTasksStmt       *sql.Stmt
	getEpisodeByIDStmt          *sql.Stmt
	getFactByIDStmt             *sql.Stmt
	getFileStmt                 *sql.Stmt
	getFileByPathAndSessionStmt *sql.Stmt
	getMessageStmt              *sql.Stmt
	getProcedureByIDStmt        *sql.Stmt
	getProcedureByNameStmt      *sql.Stmt
	getRecentTaskEventsStmt     *sql.Stmt
	getSessionByIDStmt          *sql.Stmt
	getTaskByIDStmt             *sql.Stmt
	getTaskDependenciesStmt     *sql.Stmt
	getTaskEventsStmt           *sql.Stmt
	incrementFactUsageStmt      *sql.Stmt
	listAgenciesStmt            *sql.Stmt
	listAgenciesByStatusStmt    *sql.Stmt
	listEpisodesStmt            *sql.Stmt
	listEpisodesByAgencyStmt    *sql.Stmt
	listEpisodesBySessionStmt   *sql.Stmt
	listFactsByCategoryStmt     *sql.Stmt
	listFactsByDomainStmt       *sql.Stmt
	listFilesByPathStmt         *sql.Stmt
	listFilesBySessionStmt      *sql.Stmt
	listLatestSessionFilesStmt  *sql.Stmt
	listMessagesBySessionStmt   *sql.Stmt
	listNewFilesStmt            *sql.Stmt
	listProceduresStmt          *sql.Stmt
	listProceduresByTriggerStmt *sql.Stmt
	listSessionsStmt            *sql.Stmt
	listTasksStmt               *sql.Stmt
	listTasksByAgencyStmt       *sql.Stmt
	listTasksByStatusStmt       *sql.Stmt
	removeTaskDependencyStmt    *sql.Stmt
	searchEpisodesStmt          *sql.Stmt
	searchFactsStmt             *sql.Stmt
	searchProceduresStmt        *sql.Stmt
	updateAgencyStatusStmt      *sql.Stmt
	updateFactConfidenceStmt    *sql.Stmt
	updateFileStmt              *sql.Stmt
	updateMessageStmt           *sql.Stmt
	updateProcedureStatsStmt    *sql.Stmt
	updateSessionStmt           *sql.Stmt
	updateTaskProgressStmt      *sql.Stmt
	updateTaskStatusStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		addTaskDependencyStmt:       q.addTaskDependencyStmt,
		cancelTaskStmt:              q.cancelTaskStmt,
		createAgencyStmt:            q.createAgencyStmt,
		createEpisodeStmt:           q.createEpisodeStmt,
		createFactStmt:              q.createFactStmt,
		createFileStmt:              q.createFileStmt,
		createMessageStmt:           q.createMessageStmt,
		createProcedureStmt:         q.createProcedureStmt,
		createSessionStmt:           q.createSessionStmt,
		createTaskStmt:              q.createTaskStmt,
		createTaskEventStmt:         q.createTaskEventStmt,
		deleteAgencyStmt:            q.deleteAgencyStmt,
		deleteEpisodeStmt:           q.deleteEpisodeStmt,
		deleteFactStmt:              q.deleteFactStmt,
		deleteFileStmt:              q.deleteFileStmt,
		deleteMessageStmt:           q.deleteMessageStmt,
		deleteOldEpisodesStmt:       q.deleteOldEpisodesStmt,
		deleteProcedureStmt:         q.deleteProcedureStmt,
		deleteSessionStmt:           q.deleteSessionStmt,
		deleteSessionFilesStmt:      q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:   q.deleteSessionMessagesStmt,
		deleteTaskStmt:              q.deleteTaskStmt,
		getAgencyByIDStmt:           q.getAgencyByIDStmt,
		getAgencyByNameStmt:         q.getAgencyByNameStmt,
		getDependentTasksStmt:       q.getDependentTasksStmt,
		getEpisodeByIDStmt:          q.getEpisodeByIDStmt,
		getFactByIDStmt:             q.getFactByIDStmt,
		getFileStmt:                 q.getFileStmt,
		getFileByPathAndSessionStmt: q.getFileByPathAndSessionStmt,
		getMessageStmt:              q.getMessageStmt,
		getProcedureByIDStmt:        q.getProcedureByIDStmt,
		getProcedureByNameStmt:      q.getProcedureByNameStmt,
		getRecentTaskEventsStmt:     q.getRecentTaskEventsStmt,
		getSessionByIDStmt:          q.getSessionByIDStmt,
		getTaskByIDStmt:             q.getTaskByIDStmt,
		getTaskDependenciesStmt:     q.getTaskDependenciesStmt,
		getTaskEventsStmt:           q.getTaskEventsStmt,
		incrementFactUsageStmt:      q.incrementFactUsageStmt,
		listAgenciesStmt:            q.listAgenciesStmt,
		listAgenciesByStatusStmt:    q.listAgenciesByStatusStmt,
		listEpisodesStmt:            q.listEpisodesStmt,
		listEpisodesByAgencyStmt:    q.listEpisodesByAgencyStmt,
		listEpisodesBySessionStmt:   q.listEpisodesBySessionStmt,
		listFactsByCategoryStmt:     q.listFactsByCategoryStmt,
		listFactsByDomainStmt:       q.listFactsByDomainStmt,
		listFilesByPathStmt:         q.listFilesByPathStmt,
		listFilesBySessionStmt:      q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:  q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:   q.listMessagesBySessionStmt,
		listNewFilesStmt:            q.listNewFilesStmt,
		listProceduresStmt:          q.listProceduresStmt,
		listProceduresByTriggerStmt: q.listProceduresByTriggerStmt,
		listSessionsStmt:            q.listSessionsStmt,
		listTasksStmt:               q.listTasksStmt,
		listTasksByAgencyStmt:       q.listTasksByAgencyStmt,
		listTasksByStatusStmt:       q.listTasksByStatusStmt,
		removeTaskDependencyStmt:    q.removeTaskDependencyStmt,
		searchEpisodesStmt:          q.searchEpisodesStmt,
		searchFactsStmt:             q.searchFactsStmt,
		searchProceduresStmt:        q.searchProceduresStmt,
		updateAgencyStatusStmt:      q.updateAgencyStatusStmt,
		updateFactConfidenceStmt:    q.updateFactConfidenceStmt,
		updateFileStmt:              q.updateFileStmt,
		updateMessageStmt:           q.updateMessageStmt,
		updateProcedureStatsStmt:    q.updateProcedureStatsStmt,
		updateSessionStmt:           q.updateSessionStmt,
		updateTaskProgressStmt:      q.updateTaskProgressStmt,
		updateTaskStatusStmt:        q.updateTaskStatusStmt,
	}
}
