// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeddings.sql

package db

import (
	"context"
)

const countEpisodeEmbeddings = `-- name: CountEpisodeEmbeddings :one
SELECT COUNT(*) as count FROM episode_embeddings
`

func (q *Queries) CountEpisodeEmbeddings(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countEpisodeEmbeddingsStmt, countEpisodeEmbeddings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFactEmbeddings = `-- name: CountFactEmbeddings :one
SELECT COUNT(*) as count FROM fact_embeddings
`

func (q *Queries) CountFactEmbeddings(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countFactEmbeddingsStmt, countFactEmbeddings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEpisodeEmbedding = `-- name: CreateEpisodeEmbedding :one
INSERT INTO episode_embeddings (
    id,
    episode_id,
    provider,
    model,
    dimensions,
    vector,
    text_hash,
    text_preview,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, episode_id, provider, model, dimensions, vector, text_hash, text_preview, created_at
`

type CreateEpisodeEmbeddingParams struct {
	ID          string `json:"id"`
	EpisodeID   string `json:"episode_id"`
	Provider    string `json:"provider"`
	Model       string `json:"model"`
	Dimensions  int64  `json:"dimensions"`
	Vector      []byte `json:"vector"`
	TextHash    string `json:"text_hash"`
	TextPreview string `json:"text_preview"`
}

func (q *Queries) CreateEpisodeEmbedding(ctx context.Context, arg CreateEpisodeEmbeddingParams) (EpisodeEmbedding, error) {
	row := q.queryRow(ctx, q.createEpisodeEmbeddingStmt, createEpisodeEmbedding,
		arg.ID,
		arg.EpisodeID,
		arg.Provider,
		arg.Model,
		arg.Dimensions,
		arg.Vector,
		arg.TextHash,
		arg.TextPreview,
	)
	var i EpisodeEmbedding
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Provider,
		&i.Model,
		&i.Dimensions,
		&i.Vector,
		&i.TextHash,
		&i.TextPreview,
		&i.CreatedAt,
	)
	return i, err
}

const createFactEmbedding = `-- name: CreateFactEmbedding :one
INSERT INTO fact_embeddings (
    id,
    fact_id,
    provider,
    model,
    dimensions,
    vector,
    text_hash,
    text_preview,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, fact_id, provider, model, dimensions, vector, text_hash, text_preview, created_at
`

type CreateFactEmbeddingParams struct {
	ID          string `json:"id"`
	FactID      string `json:"fact_id"`
	Provider    string `json:"provider"`
	Model       string `json:"model"`
	Dimensions  int64  `json:"dimensions"`
	Vector      []byte `json:"vector"`
	TextHash    string `json:"text_hash"`
	TextPreview string `json:"text_preview"`
}

func (q *Queries) CreateFactEmbedding(ctx context.Context, arg CreateFactEmbeddingParams) (FactEmbedding, error) {
	row := q.queryRow(ctx, q.createFactEmbeddingStmt, createFactEmbedding,
		arg.ID,
		arg.FactID,
		arg.Provider,
		arg.Model,
		arg.Dimensions,
		arg.Vector,
		arg.TextHash,
		arg.TextPreview,
	)
	var i FactEmbedding
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Provider,
		&i.Model,
		&i.Dimensions,
		&i.Vector,
		&i.TextHash,
		&i.TextPreview,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEpisodeEmbedding = `-- name: DeleteEpisodeEmbedding :exec
DELETE FROM episode_embeddings
WHERE episode_id = ?
`

func (q *Queries) DeleteEpisodeEmbedding(ctx context.Context, episodeID string) error {
	_, err := q.exec(ctx, q.deleteEpisodeEmbeddingStmt, deleteEpisodeEmbedding, episodeID)
	return err
}

const deleteFactEmbedding = `-- name: DeleteFactEmbedding :exec
DELETE FROM fact_embeddings
WHERE fact_id = ?
`

func (q *Queries) DeleteFactEmbedding(ctx context.Context, factID string) error {
	_, err := q.exec(ctx, q.deleteFactEmbeddingStmt, deleteFactEmbedding, factID)
	return err
}

const getEpisodeEmbedding = `-- name: GetEpisodeEmbedding :one
SELECT id, episode_id, provider, model, dimensions, vector, text_hash, text_preview, created_at FROM episode_embeddings
WHERE episode_id = ?
LIMIT 1
`

func (q *Queries) GetEpisodeEmbedding(ctx context.Context, episodeID string) (EpisodeEmbedding, error) {
	row := q.queryRow(ctx, q.getEpisodeEmbeddingStmt, getEpisodeEmbedding, episodeID)
	var i EpisodeEmbedding
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Provider,
		&i.Model,
		&i.Dimensions,
		&i.Vector,
		&i.TextHash,
		&i.TextPreview,
		&i.CreatedAt,
	)
	return i, err
}

const getEpisodeEmbeddingByHash = `-- name: GetEpisodeEmbeddingByHash :one
SELECT id, episode_id, provider, model, dimensions, vector, text_hash, text_preview, created_at FROM episode_embeddings
WHERE text_hash = ? AND episode_id = ?
LIMIT 1
`

type GetEpisodeEmbeddingByHashParams struct {
	TextHash  string `json:"text_hash"`
	EpisodeID string `json:"episode_id"`
}

func (q *Queries) GetEpisodeEmbeddingByHash(ctx context.Context, arg GetEpisodeEmbeddingByHashParams) (EpisodeEmbedding, error) {
	row := q.queryRow(ctx, q.getEpisodeEmbeddingByHashStmt, getEpisodeEmbeddingByHash, arg.TextHash, arg.EpisodeID)
	var i EpisodeEmbedding
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Provider,
		&i.Model,
		&i.Dimensions,
		&i.Vector,
		&i.TextHash,
		&i.TextPreview,
		&i.CreatedAt,
	)
	return i, err
}

const getFactEmbedding = `-- name: GetFactEmbedding :one
SELECT id, fact_id, provider, model, dimensions, vector, text_hash, text_preview, created_at FROM fact_embeddings
WHERE fact_id = ?
LIMIT 1
`

func (q *Queries) GetFactEmbedding(ctx context.Context, factID string) (FactEmbedding, error) {
	row := q.queryRow(ctx, q.getFactEmbeddingStmt, getFactEmbedding, factID)
	var i FactEmbedding
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Provider,
		&i.Model,
		&i.Dimensions,
		&i.Vector,
		&i.TextHash,
		&i.TextPreview,
		&i.CreatedAt,
	)
	return i, err
}

const getFactEmbeddingByHash = `-- name: GetFactEmbeddingByHash :one
SELECT id, fact_id, provider, model, dimensions, vector, text_hash, text_preview, created_at FROM fact_embeddings
WHERE text_hash = ? AND fact_id = ?
LIMIT 1
`

type GetFactEmbeddingByHashParams struct {
	TextHash string `json:"text_hash"`
	FactID   string `json:"fact_id"`
}

func (q *Queries) GetFactEmbeddingByHash(ctx context.Context, arg GetFactEmbeddingByHashParams) (FactEmbedding, error) {
	row := q.queryRow(ctx, q.getFactEmbeddingByHashStmt, getFactEmbeddingByHash, arg.TextHash, arg.FactID)
	var i FactEmbedding
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Provider,
		&i.Model,
		&i.Dimensions,
		&i.Vector,
		&i.TextHash,
		&i.TextPreview,
		&i.CreatedAt,
	)
	return i, err
}

const listEpisodeEmbeddings = `-- name: ListEpisodeEmbeddings :many
SELECT id, episode_id, provider, model, dimensions, vector, text_hash, text_preview, created_at FROM episode_embeddings
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEpisodeEmbeddingsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListEpisodeEmbeddings(ctx context.Context, arg ListEpisodeEmbeddingsParams) ([]EpisodeEmbedding, error) {
	rows, err := q.query(ctx, q.listEpisodeEmbeddingsStmt, listEpisodeEmbeddings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EpisodeEmbedding{}
	for rows.Next() {
		var i EpisodeEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.Provider,
			&i.Model,
			&i.Dimensions,
			&i.Vector,
			&i.TextHash,
			&i.TextPreview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactEmbeddings = `-- name: ListFactEmbeddings :many
SELECT id, fact_id, provider, model, dimensions, vector, text_hash, text_preview, created_at FROM fact_embeddings
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListFactEmbeddingsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListFactEmbeddings(ctx context.Context, arg ListFactEmbeddingsParams) ([]FactEmbedding, error) {
	rows, err := q.query(ctx, q.listFactEmbeddingsStmt, listFactEmbeddings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FactEmbedding{}
	for rows.Next() {
		var i FactEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.Provider,
			&i.Model,
			&i.Dimensions,
			&i.Vector,
			&i.TextHash,
			&i.TextPreview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
