// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes_adv.sql

package db

import (
	"context"
	"database/sql"
)

const countEpisodesByOutcome = `-- name: CountEpisodesByOutcome :one
SELECT
    outcome,
    COUNT(*) as count
FROM episodes
WHERE created_at >= ? AND created_at <= ?
GROUP BY outcome
`

type CountEpisodesByOutcomeParams struct {
	CreatedAt   int64 `json:"created_at"`
	CreatedAt_2 int64 `json:"created_at_2"`
}

type CountEpisodesByOutcomeRow struct {
	Outcome sql.NullString `json:"outcome"`
	Count   int64          `json:"count"`
}

func (q *Queries) CountEpisodesByOutcome(ctx context.Context, arg CountEpisodesByOutcomeParams) (CountEpisodesByOutcomeRow, error) {
	row := q.queryRow(ctx, q.countEpisodesByOutcomeStmt, countEpisodesByOutcome, arg.CreatedAt, arg.CreatedAt_2)
	var i CountEpisodesByOutcomeRow
	err := row.Scan(&i.Outcome, &i.Count)
	return i, err
}

const searchEpisodesByAgent = `-- name: SearchEpisodesByAgent :many
SELECT id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at FROM episodes
WHERE agent_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchEpisodesByAgentParams struct {
	AgentID sql.NullString `json:"agent_id"`
	Limit   int64          `json:"limit"`
	Offset  int64          `json:"offset"`
}

func (q *Queries) SearchEpisodesByAgent(ctx context.Context, arg SearchEpisodesByAgentParams) ([]Episode, error) {
	rows, err := q.query(ctx, q.searchEpisodesByAgentStmt, searchEpisodesByAgent, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgencyID,
			&i.AgentID,
			&i.Task,
			&i.Actions,
			&i.Outcome,
			&i.Feedback,
			&i.EmbeddingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEpisodesByTimeRange = `-- name: SearchEpisodesByTimeRange :many
SELECT id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at FROM episodes
WHERE created_at >= ? AND created_at <= ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchEpisodesByTimeRangeParams struct {
	CreatedAt   int64 `json:"created_at"`
	CreatedAt_2 int64 `json:"created_at_2"`
	Limit       int64 `json:"limit"`
	Offset      int64 `json:"offset"`
}

func (q *Queries) SearchEpisodesByTimeRange(ctx context.Context, arg SearchEpisodesByTimeRangeParams) ([]Episode, error) {
	rows, err := q.query(ctx, q.searchEpisodesByTimeRangeStmt, searchEpisodesByTimeRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgencyID,
			&i.AgentID,
			&i.Task,
			&i.Actions,
			&i.Outcome,
			&i.Feedback,
			&i.EmbeddingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEpisodesFull = `-- name: SearchEpisodesFull :many
SELECT id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at FROM episodes
WHERE
    (session_id = ? OR ? = '')
    AND (agency_id = ? OR ? = '')
    AND (agent_id = ? OR ? = '')
    AND (task LIKE '%' || ? || '%' OR ? = '')
    AND (created_at >= ? OR ? = 0)
    AND (created_at <= ? OR ? = 0)
ORDER BY
    CASE outcome
        WHEN 'success' THEN 1
        WHEN 'partial' THEN 2
        WHEN 'failure' THEN 3
        ELSE 4
    END,
    created_at DESC
LIMIT ? OFFSET ?
`

type SearchEpisodesFullParams struct {
	SessionID   sql.NullString `json:"session_id"`
	Column2     interface{}    `json:"column_2"`
	AgencyID    sql.NullString `json:"agency_id"`
	Column4     interface{}    `json:"column_4"`
	AgentID     sql.NullString `json:"agent_id"`
	Column6     interface{}    `json:"column_6"`
	Column7     sql.NullString `json:"column_7"`
	Column8     interface{}    `json:"column_8"`
	CreatedAt   int64          `json:"created_at"`
	Column10    interface{}    `json:"column_10"`
	CreatedAt_2 int64          `json:"created_at_2"`
	Column12    interface{}    `json:"column_12"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

// Advanced episode search with all filters
func (q *Queries) SearchEpisodesFull(ctx context.Context, arg SearchEpisodesFullParams) ([]Episode, error) {
	rows, err := q.query(ctx, q.searchEpisodesFullStmt, searchEpisodesFull,
		arg.SessionID,
		arg.Column2,
		arg.AgencyID,
		arg.Column4,
		arg.AgentID,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.CreatedAt,
		arg.Column10,
		arg.CreatedAt_2,
		arg.Column12,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgencyID,
			&i.AgentID,
			&i.Task,
			&i.Actions,
			&i.Outcome,
			&i.Feedback,
			&i.EmbeddingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
