// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package db

import (
	"context"
	"database/sql"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (
    id,
    session_id,
    agency_id,
    agent_id,
    task,
    actions,
    outcome,
    feedback,
    embedding_id,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at
`

type CreateEpisodeParams struct {
	ID          string         `json:"id"`
	SessionID   sql.NullString `json:"session_id"`
	AgencyID    sql.NullString `json:"agency_id"`
	AgentID     sql.NullString `json:"agent_id"`
	Task        sql.NullString `json:"task"`
	Actions     sql.NullString `json:"actions"`
	Outcome     sql.NullString `json:"outcome"`
	Feedback    sql.NullString `json:"feedback"`
	EmbeddingID sql.NullString `json:"embedding_id"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.queryRow(ctx, q.createEpisodeStmt, createEpisode,
		arg.ID,
		arg.SessionID,
		arg.AgencyID,
		arg.AgentID,
		arg.Task,
		arg.Actions,
		arg.Outcome,
		arg.Feedback,
		arg.EmbeddingID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgencyID,
		&i.AgentID,
		&i.Task,
		&i.Actions,
		&i.Outcome,
		&i.Feedback,
		&i.EmbeddingID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes
WHERE id = ?
`

func (q *Queries) DeleteEpisode(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteEpisodeStmt, deleteEpisode, id)
	return err
}

const deleteOldEpisodes = `-- name: DeleteOldEpisodes :exec
DELETE FROM episodes
WHERE created_at < ?
`

func (q *Queries) DeleteOldEpisodes(ctx context.Context, createdAt int64) error {
	_, err := q.exec(ctx, q.deleteOldEpisodesStmt, deleteOldEpisodes, createdAt)
	return err
}

const getEpisodeByID = `-- name: GetEpisodeByID :one
SELECT id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at
FROM episodes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetEpisodeByID(ctx context.Context, id string) (Episode, error) {
	row := q.queryRow(ctx, q.getEpisodeByIDStmt, getEpisodeByID, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgencyID,
		&i.AgentID,
		&i.Task,
		&i.Actions,
		&i.Outcome,
		&i.Feedback,
		&i.EmbeddingID,
		&i.CreatedAt,
	)
	return i, err
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at
FROM episodes
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEpisodesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListEpisodes(ctx context.Context, arg ListEpisodesParams) ([]Episode, error) {
	rows, err := q.query(ctx, q.listEpisodesStmt, listEpisodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgencyID,
			&i.AgentID,
			&i.Task,
			&i.Actions,
			&i.Outcome,
			&i.Feedback,
			&i.EmbeddingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesByAgency = `-- name: ListEpisodesByAgency :many
SELECT id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at
FROM episodes
WHERE agency_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEpisodesByAgencyParams struct {
	AgencyID sql.NullString `json:"agency_id"`
	Limit    int64          `json:"limit"`
	Offset   int64          `json:"offset"`
}

func (q *Queries) ListEpisodesByAgency(ctx context.Context, arg ListEpisodesByAgencyParams) ([]Episode, error) {
	rows, err := q.query(ctx, q.listEpisodesByAgencyStmt, listEpisodesByAgency, arg.AgencyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgencyID,
			&i.AgentID,
			&i.Task,
			&i.Actions,
			&i.Outcome,
			&i.Feedback,
			&i.EmbeddingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesBySession = `-- name: ListEpisodesBySession :many
SELECT id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at
FROM episodes
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEpisodesBySessionParams struct {
	SessionID sql.NullString `json:"session_id"`
	Limit     int64          `json:"limit"`
	Offset    int64          `json:"offset"`
}

func (q *Queries) ListEpisodesBySession(ctx context.Context, arg ListEpisodesBySessionParams) ([]Episode, error) {
	rows, err := q.query(ctx, q.listEpisodesBySessionStmt, listEpisodesBySession, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgencyID,
			&i.AgentID,
			&i.Task,
			&i.Actions,
			&i.Outcome,
			&i.Feedback,
			&i.EmbeddingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEpisodes = `-- name: SearchEpisodes :many
SELECT id, session_id, agency_id, agent_id, task, actions, outcome, feedback, embedding_id, created_at
FROM episodes
WHERE outcome LIKE '%' || ? || '%'
   OR task LIKE '%' || ? || '%'
ORDER BY created_at DESC
LIMIT ?
`

type SearchEpisodesParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchEpisodes(ctx context.Context, arg SearchEpisodesParams) ([]Episode, error) {
	rows, err := q.query(ctx, q.searchEpisodesStmt, searchEpisodes, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgencyID,
			&i.AgentID,
			&i.Task,
			&i.Actions,
			&i.Outcome,
			&i.Feedback,
			&i.EmbeddingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
