// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facts.sql

package db

import (
	"context"
	"database/sql"
)

const createFact = `-- name: CreateFact :one
INSERT INTO facts (
    id,
    domain,
    category,
    content,
    source,
    confidence,
    created_at,
    use_count
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    0
) RETURNING id, domain, category, content, source, confidence, created_at, last_used, use_count
`

type CreateFactParams struct {
	ID         string         `json:"id"`
	Domain     string         `json:"domain"`
	Category   sql.NullString `json:"category"`
	Content    string         `json:"content"`
	Source     sql.NullString `json:"source"`
	Confidence float64        `json:"confidence"`
}

func (q *Queries) CreateFact(ctx context.Context, arg CreateFactParams) (Fact, error) {
	row := q.queryRow(ctx, q.createFactStmt, createFact,
		arg.ID,
		arg.Domain,
		arg.Category,
		arg.Content,
		arg.Source,
		arg.Confidence,
	)
	var i Fact
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Category,
		&i.Content,
		&i.Source,
		&i.Confidence,
		&i.CreatedAt,
		&i.LastUsed,
		&i.UseCount,
	)
	return i, err
}

const deleteFact = `-- name: DeleteFact :exec
DELETE FROM facts
WHERE id = ?
`

func (q *Queries) DeleteFact(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteFactStmt, deleteFact, id)
	return err
}

const getFactByID = `-- name: GetFactByID :one
SELECT id, domain, category, content, source, confidence, created_at, last_used, use_count
FROM facts
WHERE id = ? LIMIT 1
`

func (q *Queries) GetFactByID(ctx context.Context, id string) (Fact, error) {
	row := q.queryRow(ctx, q.getFactByIDStmt, getFactByID, id)
	var i Fact
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Category,
		&i.Content,
		&i.Source,
		&i.Confidence,
		&i.CreatedAt,
		&i.LastUsed,
		&i.UseCount,
	)
	return i, err
}

const incrementFactUsage = `-- name: IncrementFactUsage :exec
UPDATE facts
SET use_count = use_count + 1,
    last_used = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) IncrementFactUsage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.incrementFactUsageStmt, incrementFactUsage, id)
	return err
}

const listFactsByCategory = `-- name: ListFactsByCategory :many
SELECT id, domain, category, content, source, confidence, created_at, last_used, use_count
FROM facts
WHERE category = ?
ORDER BY use_count DESC
`

func (q *Queries) ListFactsByCategory(ctx context.Context, category sql.NullString) ([]Fact, error) {
	rows, err := q.query(ctx, q.listFactsByCategoryStmt, listFactsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fact{}
	for rows.Next() {
		var i Fact
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Category,
			&i.Content,
			&i.Source,
			&i.Confidence,
			&i.CreatedAt,
			&i.LastUsed,
			&i.UseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByDomain = `-- name: ListFactsByDomain :many
SELECT id, domain, category, content, source, confidence, created_at, last_used, use_count
FROM facts
WHERE domain = ?
ORDER BY use_count DESC, created_at DESC
`

func (q *Queries) ListFactsByDomain(ctx context.Context, domain string) ([]Fact, error) {
	rows, err := q.query(ctx, q.listFactsByDomainStmt, listFactsByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fact{}
	for rows.Next() {
		var i Fact
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Category,
			&i.Content,
			&i.Source,
			&i.Confidence,
			&i.CreatedAt,
			&i.LastUsed,
			&i.UseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFacts = `-- name: SearchFacts :many
SELECT id, domain, category, content, source, confidence, created_at, last_used, use_count
FROM facts
WHERE content LIKE '%' || ? || '%'
   OR domain = ?
ORDER BY use_count DESC, confidence DESC
LIMIT ?
`

type SearchFactsParams struct {
	Column1 sql.NullString `json:"column_1"`
	Domain  string         `json:"domain"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchFacts(ctx context.Context, arg SearchFactsParams) ([]Fact, error) {
	rows, err := q.query(ctx, q.searchFactsStmt, searchFacts, arg.Column1, arg.Domain, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fact{}
	for rows.Next() {
		var i Fact
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Category,
			&i.Content,
			&i.Source,
			&i.Confidence,
			&i.CreatedAt,
			&i.LastUsed,
			&i.UseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFactConfidence = `-- name: UpdateFactConfidence :exec
UPDATE facts
SET confidence = ?
WHERE id = ?
`

type UpdateFactConfidenceParams struct {
	Confidence float64 `json:"confidence"`
	ID         string  `json:"id"`
}

func (q *Queries) UpdateFactConfidence(ctx context.Context, arg UpdateFactConfidenceParams) error {
	_, err := q.exec(ctx, q.updateFactConfidenceStmt, updateFactConfidence, arg.Confidence, arg.ID)
	return err
}
