// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package db

import (
	"context"
	"database/sql"
)

const deleteExpiredContexts = `-- name: DeleteExpiredContexts :exec
DELETE FROM working_memory_contexts
WHERE expires_at IS NOT NULL AND expires_at < strftime('%s', 'now')
`

func (q *Queries) DeleteExpiredContexts(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredContextsStmt, deleteExpiredContexts)
	return err
}

const deleteWorkingContext = `-- name: DeleteWorkingContext :exec
DELETE FROM working_memory_contexts WHERE session_id = ?
`

func (q *Queries) DeleteWorkingContext(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteWorkingContextStmt, deleteWorkingContext, sessionID)
	return err
}

const getWorkingContext = `-- name: GetWorkingContext :one
SELECT id, session_id, context_json, version, created_at, updated_at, expires_at FROM working_memory_contexts
WHERE session_id = ? AND (expires_at IS NULL OR expires_at > strftime('%s', 'now'))
LIMIT 1
`

func (q *Queries) GetWorkingContext(ctx context.Context, sessionID string) (WorkingMemoryContext, error) {
	row := q.queryRow(ctx, q.getWorkingContextStmt, getWorkingContext, sessionID)
	var i WorkingMemoryContext
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ContextJson,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const saveWorkingContext = `-- name: SaveWorkingContext :one
INSERT INTO working_memory_contexts (
    id, session_id, context_json, version, created_at, updated_at, expires_at
) VALUES (
    ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now'), ?
)
ON CONFLICT(session_id) DO UPDATE SET
    context_json = excluded.context_json,
    version = version + 1,
    updated_at = strftime('%s', 'now'),
    expires_at = excluded.expires_at
RETURNING id, session_id, context_json, version, created_at, updated_at, expires_at
`

type SaveWorkingContextParams struct {
	ID          string        `json:"id"`
	SessionID   string        `json:"session_id"`
	ContextJson string        `json:"context_json"`
	Version     int64         `json:"version"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
}

func (q *Queries) SaveWorkingContext(ctx context.Context, arg SaveWorkingContextParams) (WorkingMemoryContext, error) {
	row := q.queryRow(ctx, q.saveWorkingContextStmt, saveWorkingContext,
		arg.ID,
		arg.SessionID,
		arg.ContextJson,
		arg.Version,
		arg.ExpiresAt,
	)
	var i WorkingMemoryContext
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ContextJson,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
