// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Agency struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Domain      string         `json:"domain"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type AgencyState struct {
	ID         string         `json:"id"`
	AgencyID   string         `json:"agency_id"`
	Status     string         `json:"status"`
	LastTaskID sql.NullString `json:"last_task_id"`
	Metrics    sql.NullString `json:"metrics"`
	UpdatedAt  int64          `json:"updated_at"`
}

type Episode struct {
	ID          string         `json:"id"`
	SessionID   sql.NullString `json:"session_id"`
	AgencyID    sql.NullString `json:"agency_id"`
	AgentID     sql.NullString `json:"agent_id"`
	Task        sql.NullString `json:"task"`
	Actions     sql.NullString `json:"actions"`
	Outcome     sql.NullString `json:"outcome"`
	Feedback    sql.NullString `json:"feedback"`
	EmbeddingID sql.NullString `json:"embedding_id"`
	CreatedAt   int64          `json:"created_at"`
}

type EpisodeEmbedding struct {
	ID          string `json:"id"`
	EpisodeID   string `json:"episode_id"`
	Provider    string `json:"provider"`
	Model       string `json:"model"`
	Dimensions  int64  `json:"dimensions"`
	Vector      []byte `json:"vector"`
	TextHash    string `json:"text_hash"`
	TextPreview string `json:"text_preview"`
	CreatedAt   int64  `json:"created_at"`
}

type Fact struct {
	ID         string         `json:"id"`
	Domain     string         `json:"domain"`
	Category   sql.NullString `json:"category"`
	Content    string         `json:"content"`
	Source     sql.NullString `json:"source"`
	Confidence float64        `json:"confidence"`
	CreatedAt  int64          `json:"created_at"`
	LastUsed   sql.NullInt64  `json:"last_used"`
	UseCount   int64          `json:"use_count"`
}

type FactEmbedding struct {
	ID          string `json:"id"`
	FactID      string `json:"fact_id"`
	Provider    string `json:"provider"`
	Model       string `json:"model"`
	Dimensions  int64  `json:"dimensions"`
	Vector      []byte `json:"vector"`
	TextHash    string `json:"text_hash"`
	TextPreview string `json:"text_preview"`
	CreatedAt   int64  `json:"created_at"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   string `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type GuardrailAudit struct {
	ID            string         `json:"id"`
	ActionType    string         `json:"action_type"`
	ActionDetails sql.NullString `json:"action_details"`
	Result        string         `json:"result"`
	Reason        sql.NullString `json:"reason"`
	Timestamp     int64          `json:"timestamp"`
}

type GuardrailBudget struct {
	ActionType  string `json:"action_type"`
	BudgetLimit int64  `json:"budget_limit"`
	UsedCount   int64  `json:"used_count"`
	WindowHours int64  `json:"window_hours"`
	ResetAt     int64  `json:"reset_at"`
}

type GuardrailPreference struct {
	ID                    int64          `json:"id"`
	AllowedActions        sql.NullString `json:"allowed_actions"`
	ForbiddenActions      sql.NullString `json:"forbidden_actions"`
	NotificationLevel     string         `json:"notification_level"`
	NotifyChannels        sql.NullString `json:"notify_channels"`
	MaxDailyActions       int64          `json:"max_daily_actions"`
	MaxPendingSuggestions int64          `json:"max_pending_suggestions"`
	AutoApproveRules      sql.NullString `json:"auto_approve_rules"`
	QuietHours            sql.NullString `json:"quiet_hours"`
	ActiveHours           sql.NullString `json:"active_hours"`
	UpdatedAt             int64          `json:"updated_at"`
}

type Message struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Model      sql.NullString `json:"model"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type PermissionRequest struct {
	ID          string `json:"id"`
	AgencyID    string `json:"agency_id"`
	AgentID     string `json:"agent_id"`
	Action      string `json:"action"`
	Resource    string `json:"resource"`
	RequestedAt int64  `json:"requested_at"`
}

type PermissionResponse struct {
	RequestID   string         `json:"request_id"`
	Granted     int64          `json:"granted"`
	Level       string         `json:"level"`
	Scope       string         `json:"scope"`
	Reason      sql.NullString `json:"reason"`
	RespondedAt int64          `json:"responded_at"`
	ExpiresAt   sql.NullInt64  `json:"expires_at"`
}

type PermissionRule struct {
	ID              string        `json:"id"`
	AgencyID        string        `json:"agency_id"`
	Action          string        `json:"action"`
	ResourceType    string        `json:"resource_type"`
	ResourcePattern string        `json:"resource_pattern"`
	Level           string        `json:"level"`
	Scope           string        `json:"scope"`
	ExpiresAt       sql.NullInt64 `json:"expires_at"`
	CreatedAt       int64         `json:"created_at"`
	CreatedBy       string        `json:"created_by"`
}

type Procedure struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	TriggerType    string         `json:"trigger_type"`
	TriggerPattern sql.NullString `json:"trigger_pattern"`
	Steps          string         `json:"steps"`
	SuccessRate    float64        `json:"success_rate"`
	UseCount       int64          `json:"use_count"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
}

type Task struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Type         string         `json:"type"`
	Priority     int64          `json:"priority"`
	ScheduledAt  sql.NullInt64  `json:"scheduled_at"`
	Deadline     sql.NullInt64  `json:"deadline"`
	ScheduleExpr sql.NullString `json:"schedule_expr"`
	Agency       sql.NullString `json:"agency"`
	Agent        sql.NullString `json:"agent"`
	Skills       sql.NullString `json:"skills"`
	Parameters   sql.NullString `json:"parameters"`
	Status       string         `json:"status"`
	Progress     float64        `json:"progress"`
	CreatedAt    int64          `json:"created_at"`
	StartedAt    sql.NullInt64  `json:"started_at"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	Result       sql.NullString `json:"result"`
	Error        sql.NullString `json:"error"`
}

type TaskDependency struct {
	TaskID    string `json:"task_id"`
	DependsOn string `json:"depends_on"`
}

type TaskEvent struct {
	ID        string         `json:"id"`
	TaskID    string         `json:"task_id"`
	EventType string         `json:"event_type"`
	EventData sql.NullString `json:"event_data"`
	CreatedAt int64          `json:"created_at"`
}

type WorkingMemoryContext struct {
	ID          string        `json:"id"`
	SessionID   string        `json:"session_id"`
	ContextJson string        `json:"context_json"`
	Version     int64         `json:"version"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
}
