// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_guardrail.sql

package db

import (
	"context"
	"database/sql"
)

const createGuardrailAuditEntry = `-- name: CreateGuardrailAuditEntry :one

INSERT INTO guardrail_audit (
    id,
    action_type,
    action_details,
    result,
    reason,
    timestamp
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, action_type, action_details, result, reason, timestamp
`

type CreateGuardrailAuditEntryParams struct {
	ID            string         `json:"id"`
	ActionType    string         `json:"action_type"`
	ActionDetails sql.NullString `json:"action_details"`
	Result        string         `json:"result"`
	Reason        sql.NullString `json:"reason"`
}

// Guardrail Audit queries
func (q *Queries) CreateGuardrailAuditEntry(ctx context.Context, arg CreateGuardrailAuditEntryParams) (GuardrailAudit, error) {
	row := q.queryRow(ctx, q.createGuardrailAuditEntryStmt, createGuardrailAuditEntry,
		arg.ID,
		arg.ActionType,
		arg.ActionDetails,
		arg.Result,
		arg.Reason,
	)
	var i GuardrailAudit
	err := row.Scan(
		&i.ID,
		&i.ActionType,
		&i.ActionDetails,
		&i.Result,
		&i.Reason,
		&i.Timestamp,
	)
	return i, err
}

const createPermissionRequest = `-- name: CreatePermissionRequest :one

INSERT INTO permission_requests (
    id,
    agency_id,
    agent_id,
    action,
    resource,
    requested_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, agency_id, agent_id, "action", resource, requested_at
`

type CreatePermissionRequestParams struct {
	ID       string `json:"id"`
	AgencyID string `json:"agency_id"`
	AgentID  string `json:"agent_id"`
	Action   string `json:"action"`
	Resource string `json:"resource"`
}

// Permission Requests queries
func (q *Queries) CreatePermissionRequest(ctx context.Context, arg CreatePermissionRequestParams) (PermissionRequest, error) {
	row := q.queryRow(ctx, q.createPermissionRequestStmt, createPermissionRequest,
		arg.ID,
		arg.AgencyID,
		arg.AgentID,
		arg.Action,
		arg.Resource,
	)
	var i PermissionRequest
	err := row.Scan(
		&i.ID,
		&i.AgencyID,
		&i.AgentID,
		&i.Action,
		&i.Resource,
		&i.RequestedAt,
	)
	return i, err
}

const createPermissionResponse = `-- name: CreatePermissionResponse :one

INSERT INTO permission_responses (
    request_id,
    granted,
    level,
    scope,
    reason,
    responded_at,
    expires_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    ?
) RETURNING request_id, granted, level, scope, reason, responded_at, expires_at
`

type CreatePermissionResponseParams struct {
	RequestID string         `json:"request_id"`
	Granted   int64          `json:"granted"`
	Level     string         `json:"level"`
	Scope     string         `json:"scope"`
	Reason    sql.NullString `json:"reason"`
	ExpiresAt sql.NullInt64  `json:"expires_at"`
}

// Permission Responses queries
func (q *Queries) CreatePermissionResponse(ctx context.Context, arg CreatePermissionResponseParams) (PermissionResponse, error) {
	row := q.queryRow(ctx, q.createPermissionResponseStmt, createPermissionResponse,
		arg.RequestID,
		arg.Granted,
		arg.Level,
		arg.Scope,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i PermissionResponse
	err := row.Scan(
		&i.RequestID,
		&i.Granted,
		&i.Level,
		&i.Scope,
		&i.Reason,
		&i.RespondedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createPermissionRule = `-- name: CreatePermissionRule :one

INSERT INTO permission_rules (
    id,
    agency_id,
    action,
    resource_type,
    resource_pattern,
    level,
    scope,
    expires_at,
    created_at,
    created_by
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    ?
) RETURNING id, agency_id, "action", resource_type, resource_pattern, level, scope, expires_at, created_at, created_by
`

type CreatePermissionRuleParams struct {
	ID              string        `json:"id"`
	AgencyID        string        `json:"agency_id"`
	Action          string        `json:"action"`
	ResourceType    string        `json:"resource_type"`
	ResourcePattern string        `json:"resource_pattern"`
	Level           string        `json:"level"`
	Scope           string        `json:"scope"`
	ExpiresAt       sql.NullInt64 `json:"expires_at"`
	CreatedBy       string        `json:"created_by"`
}

// Permission Rules queries
func (q *Queries) CreatePermissionRule(ctx context.Context, arg CreatePermissionRuleParams) (PermissionRule, error) {
	row := q.queryRow(ctx, q.createPermissionRuleStmt, createPermissionRule,
		arg.ID,
		arg.AgencyID,
		arg.Action,
		arg.ResourceType,
		arg.ResourcePattern,
		arg.Level,
		arg.Scope,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i PermissionRule
	err := row.Scan(
		&i.ID,
		&i.AgencyID,
		&i.Action,
		&i.ResourceType,
		&i.ResourcePattern,
		&i.Level,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteExpiredPermissionRules = `-- name: DeleteExpiredPermissionRules :exec
DELETE FROM permission_rules
WHERE expires_at IS NOT NULL AND expires_at < strftime('%s', 'now')
`

func (q *Queries) DeleteExpiredPermissionRules(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredPermissionRulesStmt, deleteExpiredPermissionRules)
	return err
}

const deleteOldGuardrailAudit = `-- name: DeleteOldGuardrailAudit :exec
DELETE FROM guardrail_audit
WHERE timestamp < strftime('%s', 'now', '-' || ? || ' seconds')
`

func (q *Queries) DeleteOldGuardrailAudit(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.exec(ctx, q.deleteOldGuardrailAuditStmt, deleteOldGuardrailAudit, dollar_1)
	return err
}

const deleteOldPermissionRequests = `-- name: DeleteOldPermissionRequests :exec
DELETE FROM permission_requests
WHERE requested_at < strftime('%s', 'now', '-' || ? || ' seconds')
`

func (q *Queries) DeleteOldPermissionRequests(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.exec(ctx, q.deleteOldPermissionRequestsStmt, deleteOldPermissionRequests, dollar_1)
	return err
}

const deletePermissionRule = `-- name: DeletePermissionRule :exec
DELETE FROM permission_rules
WHERE id = ?
`

func (q *Queries) DeletePermissionRule(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deletePermissionRuleStmt, deletePermissionRule, id)
	return err
}

const getGuardrailBudget = `-- name: GetGuardrailBudget :one
SELECT action_type, budget_limit, used_count, window_hours, reset_at
FROM guardrail_budgets
WHERE action_type = ? LIMIT 1
`

func (q *Queries) GetGuardrailBudget(ctx context.Context, actionType string) (GuardrailBudget, error) {
	row := q.queryRow(ctx, q.getGuardrailBudgetStmt, getGuardrailBudget, actionType)
	var i GuardrailBudget
	err := row.Scan(
		&i.ActionType,
		&i.BudgetLimit,
		&i.UsedCount,
		&i.WindowHours,
		&i.ResetAt,
	)
	return i, err
}

const getGuardrailPreferences = `-- name: GetGuardrailPreferences :one
SELECT id, allowed_actions, forbidden_actions, notification_level, notify_channels, max_daily_actions, max_pending_suggestions, auto_approve_rules, quiet_hours, active_hours, updated_at
FROM guardrail_preferences
WHERE id = 1 LIMIT 1
`

func (q *Queries) GetGuardrailPreferences(ctx context.Context) (GuardrailPreference, error) {
	row := q.queryRow(ctx, q.getGuardrailPreferencesStmt, getGuardrailPreferences)
	var i GuardrailPreference
	err := row.Scan(
		&i.ID,
		&i.AllowedActions,
		&i.ForbiddenActions,
		&i.NotificationLevel,
		&i.NotifyChannels,
		&i.MaxDailyActions,
		&i.MaxPendingSuggestions,
		&i.AutoApproveRules,
		&i.QuietHours,
		&i.ActiveHours,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionRequestByID = `-- name: GetPermissionRequestByID :one
SELECT id, agency_id, agent_id, "action", resource, requested_at
FROM permission_requests
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPermissionRequestByID(ctx context.Context, id string) (PermissionRequest, error) {
	row := q.queryRow(ctx, q.getPermissionRequestByIDStmt, getPermissionRequestByID, id)
	var i PermissionRequest
	err := row.Scan(
		&i.ID,
		&i.AgencyID,
		&i.AgentID,
		&i.Action,
		&i.Resource,
		&i.RequestedAt,
	)
	return i, err
}

const getPermissionResponseByRequestID = `-- name: GetPermissionResponseByRequestID :one
SELECT request_id, granted, level, scope, reason, responded_at, expires_at
FROM permission_responses
WHERE request_id = ? LIMIT 1
`

func (q *Queries) GetPermissionResponseByRequestID(ctx context.Context, requestID string) (PermissionResponse, error) {
	row := q.queryRow(ctx, q.getPermissionResponseByRequestIDStmt, getPermissionResponseByRequestID, requestID)
	var i PermissionResponse
	err := row.Scan(
		&i.RequestID,
		&i.Granted,
		&i.Level,
		&i.Scope,
		&i.Reason,
		&i.RespondedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPermissionRuleByID = `-- name: GetPermissionRuleByID :one
SELECT id, agency_id, "action", resource_type, resource_pattern, level, scope, expires_at, created_at, created_by
FROM permission_rules
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPermissionRuleByID(ctx context.Context, id string) (PermissionRule, error) {
	row := q.queryRow(ctx, q.getPermissionRuleByIDStmt, getPermissionRuleByID, id)
	var i PermissionRule
	err := row.Scan(
		&i.ID,
		&i.AgencyID,
		&i.Action,
		&i.ResourceType,
		&i.ResourcePattern,
		&i.Level,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listGuardrailAuditByTimeRange = `-- name: ListGuardrailAuditByTimeRange :many
SELECT id, action_type, action_details, result, reason, timestamp
FROM guardrail_audit
WHERE timestamp >= ? AND timestamp <= ?
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type ListGuardrailAuditByTimeRangeParams struct {
	Timestamp   int64 `json:"timestamp"`
	Timestamp_2 int64 `json:"timestamp_2"`
	Limit       int64 `json:"limit"`
	Offset      int64 `json:"offset"`
}

func (q *Queries) ListGuardrailAuditByTimeRange(ctx context.Context, arg ListGuardrailAuditByTimeRangeParams) ([]GuardrailAudit, error) {
	rows, err := q.query(ctx, q.listGuardrailAuditByTimeRangeStmt, listGuardrailAuditByTimeRange,
		arg.Timestamp,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuardrailAudit{}
	for rows.Next() {
		var i GuardrailAudit
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.ActionDetails,
			&i.Result,
			&i.Reason,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardrailAuditByType = `-- name: ListGuardrailAuditByType :many
SELECT id, action_type, action_details, result, reason, timestamp
FROM guardrail_audit
WHERE action_type = ?
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type ListGuardrailAuditByTypeParams struct {
	ActionType string `json:"action_type"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListGuardrailAuditByType(ctx context.Context, arg ListGuardrailAuditByTypeParams) ([]GuardrailAudit, error) {
	rows, err := q.query(ctx, q.listGuardrailAuditByTypeStmt, listGuardrailAuditByType, arg.ActionType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuardrailAudit{}
	for rows.Next() {
		var i GuardrailAudit
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.ActionDetails,
			&i.Result,
			&i.Reason,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardrailBudgets = `-- name: ListGuardrailBudgets :many
SELECT action_type, budget_limit, used_count, window_hours, reset_at
FROM guardrail_budgets
`

func (q *Queries) ListGuardrailBudgets(ctx context.Context) ([]GuardrailBudget, error) {
	rows, err := q.query(ctx, q.listGuardrailBudgetsStmt, listGuardrailBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuardrailBudget{}
	for rows.Next() {
		var i GuardrailBudget
		if err := rows.Scan(
			&i.ActionType,
			&i.BudgetLimit,
			&i.UsedCount,
			&i.WindowHours,
			&i.ResetAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionRequestsByAgency = `-- name: ListPermissionRequestsByAgency :many
SELECT id, agency_id, agent_id, "action", resource, requested_at
FROM permission_requests
WHERE agency_id = ?
ORDER BY requested_at DESC
LIMIT ? OFFSET ?
`

type ListPermissionRequestsByAgencyParams struct {
	AgencyID string `json:"agency_id"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) ListPermissionRequestsByAgency(ctx context.Context, arg ListPermissionRequestsByAgencyParams) ([]PermissionRequest, error) {
	rows, err := q.query(ctx, q.listPermissionRequestsByAgencyStmt, listPermissionRequestsByAgency, arg.AgencyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionRequest{}
	for rows.Next() {
		var i PermissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.AgencyID,
			&i.AgentID,
			&i.Action,
			&i.Resource,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionRequestsByAgent = `-- name: ListPermissionRequestsByAgent :many
SELECT id, agency_id, agent_id, "action", resource, requested_at
FROM permission_requests
WHERE agent_id = ?
ORDER BY requested_at DESC
LIMIT ? OFFSET ?
`

type ListPermissionRequestsByAgentParams struct {
	AgentID string `json:"agent_id"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListPermissionRequestsByAgent(ctx context.Context, arg ListPermissionRequestsByAgentParams) ([]PermissionRequest, error) {
	rows, err := q.query(ctx, q.listPermissionRequestsByAgentStmt, listPermissionRequestsByAgent, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionRequest{}
	for rows.Next() {
		var i PermissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.AgencyID,
			&i.AgentID,
			&i.Action,
			&i.Resource,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionRulesByAgency = `-- name: ListPermissionRulesByAgency :many
SELECT id, agency_id, "action", resource_type, resource_pattern, level, scope, expires_at, created_at, created_by
FROM permission_rules
WHERE agency_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListPermissionRulesByAgency(ctx context.Context, agencyID string) ([]PermissionRule, error) {
	rows, err := q.query(ctx, q.listPermissionRulesByAgencyStmt, listPermissionRulesByAgency, agencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionRule{}
	for rows.Next() {
		var i PermissionRule
		if err := rows.Scan(
			&i.ID,
			&i.AgencyID,
			&i.Action,
			&i.ResourceType,
			&i.ResourcePattern,
			&i.Level,
			&i.Scope,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetGuardrailBudgets = `-- name: ResetGuardrailBudgets :exec
UPDATE guardrail_budgets
SET used_count = 0,
    reset_at = ?
WHERE reset_at < strftime('%s', 'now')
`

func (q *Queries) ResetGuardrailBudgets(ctx context.Context, resetAt int64) error {
	_, err := q.exec(ctx, q.resetGuardrailBudgetsStmt, resetGuardrailBudgets, resetAt)
	return err
}

const updateGuardrailBudgetUsed = `-- name: UpdateGuardrailBudgetUsed :exec
UPDATE guardrail_budgets
SET used_count = used_count + ?
WHERE action_type = ?
`

type UpdateGuardrailBudgetUsedParams struct {
	UsedCount  int64  `json:"used_count"`
	ActionType string `json:"action_type"`
}

func (q *Queries) UpdateGuardrailBudgetUsed(ctx context.Context, arg UpdateGuardrailBudgetUsedParams) error {
	_, err := q.exec(ctx, q.updateGuardrailBudgetUsedStmt, updateGuardrailBudgetUsed, arg.UsedCount, arg.ActionType)
	return err
}

const upsertGuardrailBudget = `-- name: UpsertGuardrailBudget :one

INSERT INTO guardrail_budgets (
    action_type,
    budget_limit,
    used_count,
    window_hours,
    reset_at
) VALUES (
    ?,
    ?,
    COALESCE(?, 0),
    ?,
    ?
) ON CONFLICT(action_type) DO UPDATE SET
    budget_limit = excluded.budget_limit,
    used_count = excluded.used_count,
    window_hours = excluded.window_hours,
    reset_at = excluded.reset_at
RETURNING action_type, budget_limit, used_count, window_hours, reset_at
`

type UpsertGuardrailBudgetParams struct {
	ActionType  string      `json:"action_type"`
	BudgetLimit int64       `json:"budget_limit"`
	Column3     interface{} `json:"column_3"`
	WindowHours int64       `json:"window_hours"`
	ResetAt     int64       `json:"reset_at"`
}

// Guardrail Budgets queries
func (q *Queries) UpsertGuardrailBudget(ctx context.Context, arg UpsertGuardrailBudgetParams) (GuardrailBudget, error) {
	row := q.queryRow(ctx, q.upsertGuardrailBudgetStmt, upsertGuardrailBudget,
		arg.ActionType,
		arg.BudgetLimit,
		arg.Column3,
		arg.WindowHours,
		arg.ResetAt,
	)
	var i GuardrailBudget
	err := row.Scan(
		&i.ActionType,
		&i.BudgetLimit,
		&i.UsedCount,
		&i.WindowHours,
		&i.ResetAt,
	)
	return i, err
}

const upsertGuardrailPreferences = `-- name: UpsertGuardrailPreferences :one

INSERT INTO guardrail_preferences (
    id,
    allowed_actions,
    forbidden_actions,
    notification_level,
    notify_channels,
    max_daily_actions,
    max_pending_suggestions,
    auto_approve_rules,
    quiet_hours,
    active_hours,
    updated_at
) VALUES (
    1,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) ON CONFLICT(id) DO UPDATE SET
    allowed_actions = excluded.allowed_actions,
    forbidden_actions = excluded.forbidden_actions,
    notification_level = excluded.notification_level,
    notify_channels = excluded.notify_channels,
    max_daily_actions = excluded.max_daily_actions,
    max_pending_suggestions = excluded.max_pending_suggestions,
    auto_approve_rules = excluded.auto_approve_rules,
    quiet_hours = excluded.quiet_hours,
    active_hours = excluded.active_hours,
    updated_at = excluded.updated_at
RETURNING id, allowed_actions, forbidden_actions, notification_level, notify_channels, max_daily_actions, max_pending_suggestions, auto_approve_rules, quiet_hours, active_hours, updated_at
`

type UpsertGuardrailPreferencesParams struct {
	AllowedActions        sql.NullString `json:"allowed_actions"`
	ForbiddenActions      sql.NullString `json:"forbidden_actions"`
	NotificationLevel     string         `json:"notification_level"`
	NotifyChannels        sql.NullString `json:"notify_channels"`
	MaxDailyActions       int64          `json:"max_daily_actions"`
	MaxPendingSuggestions int64          `json:"max_pending_suggestions"`
	AutoApproveRules      sql.NullString `json:"auto_approve_rules"`
	QuietHours            sql.NullString `json:"quiet_hours"`
	ActiveHours           sql.NullString `json:"active_hours"`
}

// Guardrail Preferences queries
func (q *Queries) UpsertGuardrailPreferences(ctx context.Context, arg UpsertGuardrailPreferencesParams) (GuardrailPreference, error) {
	row := q.queryRow(ctx, q.upsertGuardrailPreferencesStmt, upsertGuardrailPreferences,
		arg.AllowedActions,
		arg.ForbiddenActions,
		arg.NotificationLevel,
		arg.NotifyChannels,
		arg.MaxDailyActions,
		arg.MaxPendingSuggestions,
		arg.AutoApproveRules,
		arg.QuietHours,
		arg.ActiveHours,
	)
	var i GuardrailPreference
	err := row.Scan(
		&i.ID,
		&i.AllowedActions,
		&i.ForbiddenActions,
		&i.NotificationLevel,
		&i.NotifyChannels,
		&i.MaxDailyActions,
		&i.MaxPendingSuggestions,
		&i.AutoApproveRules,
		&i.QuietHours,
		&i.ActiveHours,
		&i.UpdatedAt,
	)
	return i, err
}
