// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: procedures.sql

package db

import (
	"context"
	"database/sql"
)

const createProcedure = `-- name: CreateProcedure :one
INSERT INTO procedures (
    id,
    name,
    description,
    trigger_type,
    trigger_pattern,
    steps,
    success_rate,
    use_count,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    0.0,
    0,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, name, description, trigger_type, trigger_pattern, steps, success_rate, use_count, created_at, updated_at
`

type CreateProcedureParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	TriggerType    string         `json:"trigger_type"`
	TriggerPattern sql.NullString `json:"trigger_pattern"`
	Steps          string         `json:"steps"`
}

func (q *Queries) CreateProcedure(ctx context.Context, arg CreateProcedureParams) (Procedure, error) {
	row := q.queryRow(ctx, q.createProcedureStmt, createProcedure,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.TriggerPattern,
		arg.Steps,
	)
	var i Procedure
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TriggerPattern,
		&i.Steps,
		&i.SuccessRate,
		&i.UseCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProcedure = `-- name: DeleteProcedure :exec
DELETE FROM procedures
WHERE id = ?
`

func (q *Queries) DeleteProcedure(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProcedureStmt, deleteProcedure, id)
	return err
}

const getProcedureByID = `-- name: GetProcedureByID :one
SELECT id, name, description, trigger_type, trigger_pattern, steps, success_rate, use_count, created_at, updated_at
FROM procedures
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProcedureByID(ctx context.Context, id string) (Procedure, error) {
	row := q.queryRow(ctx, q.getProcedureByIDStmt, getProcedureByID, id)
	var i Procedure
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TriggerPattern,
		&i.Steps,
		&i.SuccessRate,
		&i.UseCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProcedureByName = `-- name: GetProcedureByName :one
SELECT id, name, description, trigger_type, trigger_pattern, steps, success_rate, use_count, created_at, updated_at
FROM procedures
WHERE name = ? LIMIT 1
`

func (q *Queries) GetProcedureByName(ctx context.Context, name string) (Procedure, error) {
	row := q.queryRow(ctx, q.getProcedureByNameStmt, getProcedureByName, name)
	var i Procedure
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TriggerPattern,
		&i.Steps,
		&i.SuccessRate,
		&i.UseCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProcedures = `-- name: ListProcedures :many
SELECT id, name, description, trigger_type, trigger_pattern, steps, success_rate, use_count, created_at, updated_at
FROM procedures
ORDER BY use_count DESC, name ASC
`

func (q *Queries) ListProcedures(ctx context.Context) ([]Procedure, error) {
	rows, err := q.query(ctx, q.listProceduresStmt, listProcedures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Procedure{}
	for rows.Next() {
		var i Procedure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.TriggerPattern,
			&i.Steps,
			&i.SuccessRate,
			&i.UseCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProceduresByTrigger = `-- name: ListProceduresByTrigger :many
SELECT id, name, description, trigger_type, trigger_pattern, steps, success_rate, use_count, created_at, updated_at
FROM procedures
WHERE trigger_type = ?
ORDER BY success_rate DESC, use_count DESC
`

func (q *Queries) ListProceduresByTrigger(ctx context.Context, triggerType string) ([]Procedure, error) {
	rows, err := q.query(ctx, q.listProceduresByTriggerStmt, listProceduresByTrigger, triggerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Procedure{}
	for rows.Next() {
		var i Procedure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.TriggerPattern,
			&i.Steps,
			&i.SuccessRate,
			&i.UseCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProcedures = `-- name: SearchProcedures :many
SELECT id, name, description, trigger_type, trigger_pattern, steps, success_rate, use_count, created_at, updated_at
FROM procedures
WHERE name LIKE '%' || ? || '%'
   OR description LIKE '%' || ? || '%'
ORDER BY success_rate DESC
`

type SearchProceduresParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
}

func (q *Queries) SearchProcedures(ctx context.Context, arg SearchProceduresParams) ([]Procedure, error) {
	rows, err := q.query(ctx, q.searchProceduresStmt, searchProcedures, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Procedure{}
	for rows.Next() {
		var i Procedure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.TriggerPattern,
			&i.Steps,
			&i.SuccessRate,
			&i.UseCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcedureStats = `-- name: UpdateProcedureStats :exec
UPDATE procedures
SET success_rate = ?,
    use_count = use_count + 1,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateProcedureStatsParams struct {
	SuccessRate float64 `json:"success_rate"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateProcedureStats(ctx context.Context, arg UpdateProcedureStatsParams) error {
	_, err := q.exec(ctx, q.updateProcedureStatsStmt, updateProcedureStats, arg.SuccessRate, arg.ID)
	return err
}
