// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error
	CancelTask(ctx context.Context, id string) error
	CountEpisodesByOutcome(ctx context.Context, arg CountEpisodesByOutcomeParams) (CountEpisodesByOutcomeRow, error)
	CountTasksByStatus(ctx context.Context, status string) (int64, error)
	CreateAgency(ctx context.Context, arg CreateAgencyParams) (Agency, error)
	CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error)
	CreateFact(ctx context.Context, arg CreateFactParams) (Fact, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateProcedure(ctx context.Context, arg CreateProcedureParams) (Procedure, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTaskEvent(ctx context.Context, arg CreateTaskEventParams) (TaskEvent, error)
	DeleteAgency(ctx context.Context, id string) error
	DeleteAgencyState(ctx context.Context, agencyID string) error
	DeleteEpisode(ctx context.Context, id string) error
	DeleteExpiredContexts(ctx context.Context) error
	DeleteFact(ctx context.Context, id string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteOldEpisodes(ctx context.Context, createdAt int64) error
	DeleteProcedure(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	DeleteTask(ctx context.Context, id string) error
	DeleteWorkingContext(ctx context.Context, sessionID string) error
	GetAgencyByID(ctx context.Context, id string) (Agency, error)
	GetAgencyByName(ctx context.Context, name string) (Agency, error)
	GetAgencyState(ctx context.Context, agencyID string) (AgencyState, error)
	GetDependentTasks(ctx context.Context, dependsOn string) ([]Task, error)
	GetEpisodeByID(ctx context.Context, id string) (Episode, error)
	GetFactByID(ctx context.Context, id string) (Fact, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetProcedureByID(ctx context.Context, id string) (Procedure, error)
	GetProcedureByName(ctx context.Context, name string) (Procedure, error)
	GetRecentTaskEvents(ctx context.Context, limit int64) ([]TaskEvent, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetTaskByID(ctx context.Context, id string) (Task, error)
	GetTaskDependencies(ctx context.Context, taskID string) ([]Task, error)
	GetTaskEvents(ctx context.Context, taskID string) ([]TaskEvent, error)
	GetWorkingContext(ctx context.Context, sessionID string) (WorkingMemoryContext, error)
	IncrementFactUsage(ctx context.Context, id string) error
	ListAgencies(ctx context.Context) ([]Agency, error)
	ListAgenciesByStatus(ctx context.Context, status string) ([]Agency, error)
	ListEpisodes(ctx context.Context, arg ListEpisodesParams) ([]Episode, error)
	ListEpisodesByAgency(ctx context.Context, arg ListEpisodesByAgencyParams) ([]Episode, error)
	ListEpisodesBySession(ctx context.Context, arg ListEpisodesBySessionParams) ([]Episode, error)
	ListFactsByCategory(ctx context.Context, category sql.NullString) ([]Fact, error)
	ListFactsByDomain(ctx context.Context, domain string) ([]Fact, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListPendingTasks(ctx context.Context, arg ListPendingTasksParams) ([]Task, error)
	ListProcedures(ctx context.Context) ([]Procedure, error)
	ListProceduresByTrigger(ctx context.Context, triggerType string) ([]Procedure, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTasksByAgency(ctx context.Context, arg ListTasksByAgencyParams) ([]Task, error)
	ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error)
	RemoveTaskDependency(ctx context.Context, arg RemoveTaskDependencyParams) error
	SaveWorkingContext(ctx context.Context, arg SaveWorkingContextParams) (WorkingMemoryContext, error)
	SearchEpisodes(ctx context.Context, arg SearchEpisodesParams) ([]Episode, error)
	SearchEpisodesByAgent(ctx context.Context, arg SearchEpisodesByAgentParams) ([]Episode, error)
	SearchEpisodesByTimeRange(ctx context.Context, arg SearchEpisodesByTimeRangeParams) ([]Episode, error)
	// Advanced episode search with all filters
	SearchEpisodesFull(ctx context.Context, arg SearchEpisodesFullParams) ([]Episode, error)
	SearchFacts(ctx context.Context, arg SearchFactsParams) ([]Fact, error)
	SearchProcedures(ctx context.Context, arg SearchProceduresParams) ([]Procedure, error)
	UpdateAgencyStatus(ctx context.Context, arg UpdateAgencyStatusParams) error
	UpdateFactConfidence(ctx context.Context, arg UpdateFactConfidenceParams) error
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateProcedureStats(ctx context.Context, arg UpdateProcedureStatsParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpsertAgencyState(ctx context.Context, arg UpsertAgencyStateParams) (AgencyState, error)
}

var _ Querier = (*Queries)(nil)
