// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_events.sql

package db

import (
	"context"
	"database/sql"
)

const createTaskEvent = `-- name: CreateTaskEvent :one
INSERT INTO task_events (
    id,
    task_id,
    event_type,
    event_data,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) RETURNING id, task_id, event_type, event_data, created_at
`

type CreateTaskEventParams struct {
	ID        string         `json:"id"`
	TaskID    string         `json:"task_id"`
	EventType string         `json:"event_type"`
	EventData sql.NullString `json:"event_data"`
}

func (q *Queries) CreateTaskEvent(ctx context.Context, arg CreateTaskEventParams) (TaskEvent, error) {
	row := q.queryRow(ctx, q.createTaskEventStmt, createTaskEvent,
		arg.ID,
		arg.TaskID,
		arg.EventType,
		arg.EventData,
	)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.EventType,
		&i.EventData,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentTaskEvents = `-- name: GetRecentTaskEvents :many
SELECT id, task_id, event_type, event_data, created_at
FROM task_events
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetRecentTaskEvents(ctx context.Context, limit int64) ([]TaskEvent, error) {
	rows, err := q.query(ctx, q.getRecentTaskEventsStmt, getRecentTaskEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskEvents = `-- name: GetTaskEvents :many
SELECT id, task_id, event_type, event_data, created_at
FROM task_events
WHERE task_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetTaskEvents(ctx context.Context, taskID string) ([]TaskEvent, error) {
	rows, err := q.query(ctx, q.getTaskEventsStmt, getTaskEvents, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
