// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const addTaskDependency = `-- name: AddTaskDependency :exec
INSERT INTO task_dependencies (task_id, depends_on)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddTaskDependencyParams struct {
	TaskID    string `json:"task_id"`
	DependsOn string `json:"depends_on"`
}

func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error {
	_, err := q.exec(ctx, q.addTaskDependencyStmt, addTaskDependency, arg.TaskID, arg.DependsOn)
	return err
}

const cancelTask = `-- name: CancelTask :exec
UPDATE tasks
SET status = 'cancelled',
    completed_at = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) CancelTask(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.cancelTaskStmt, cancelTask, id)
	return err
}

const countTasksByStatus = `-- name: CountTasksByStatus :one
SELECT COUNT(*)
FROM tasks
WHERE status = ?
`

func (q *Queries) CountTasksByStatus(ctx context.Context, status string) (int64, error) {
	row := q.queryRow(ctx, q.countTasksByStatusStmt, countTasksByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id,
    name,
    description,
    type,
    priority,
    scheduled_at,
    deadline,
    schedule_expr,
    agency,
    agent,
    skills,
    parameters,
    status,
    progress,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    'created',
    0.0,
    strftime('%s', 'now')
) RETURNING id, name, description, type, priority, scheduled_at, deadline, schedule_expr, agency, agent, skills, parameters, status, progress, created_at, started_at, completed_at, result, error
`

type CreateTaskParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Type         string         `json:"type"`
	Priority     int64          `json:"priority"`
	ScheduledAt  sql.NullInt64  `json:"scheduled_at"`
	Deadline     sql.NullInt64  `json:"deadline"`
	ScheduleExpr sql.NullString `json:"schedule_expr"`
	Agency       sql.NullString `json:"agency"`
	Agent        sql.NullString `json:"agent"`
	Skills       sql.NullString `json:"skills"`
	Parameters   sql.NullString `json:"parameters"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.createTaskStmt, createTask,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Priority,
		arg.ScheduledAt,
		arg.Deadline,
		arg.ScheduleExpr,
		arg.Agency,
		arg.Agent,
		arg.Skills,
		arg.Parameters,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Priority,
		&i.ScheduledAt,
		&i.Deadline,
		&i.ScheduleExpr,
		&i.Agency,
		&i.Agent,
		&i.Skills,
		&i.Parameters,
		&i.Status,
		&i.Progress,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteTaskStmt, deleteTask, id)
	return err
}

const getDependentTasks = `-- name: GetDependentTasks :many
SELECT t.id, t.name, t.description, t.type, t.priority, t.scheduled_at, t.deadline, t.schedule_expr, t.agency, t.agent, t.skills, t.parameters, t.status, t.progress, t.created_at, t.started_at, t.completed_at, t.result, t.error
FROM tasks t
INNER JOIN task_dependencies td ON t.id = td.task_id
WHERE td.depends_on = ?
`

func (q *Queries) GetDependentTasks(ctx context.Context, dependsOn string) ([]Task, error) {
	rows, err := q.query(ctx, q.getDependentTasksStmt, getDependentTasks, dependsOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Priority,
			&i.ScheduledAt,
			&i.Deadline,
			&i.ScheduleExpr,
			&i.Agency,
			&i.Agent,
			&i.Skills,
			&i.Parameters,
			&i.Status,
			&i.Progress,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, name, description, type, priority, scheduled_at, deadline, schedule_expr, agency, agent, skills, parameters, status, progress, created_at, started_at, completed_at, result, error
FROM tasks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.queryRow(ctx, q.getTaskByIDStmt, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Priority,
		&i.ScheduledAt,
		&i.Deadline,
		&i.ScheduleExpr,
		&i.Agency,
		&i.Agent,
		&i.Skills,
		&i.Parameters,
		&i.Status,
		&i.Progress,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const getTaskDependencies = `-- name: GetTaskDependencies :many
SELECT t.id, t.name, t.description, t.type, t.priority, t.scheduled_at, t.deadline, t.schedule_expr, t.agency, t.agent, t.skills, t.parameters, t.status, t.progress, t.created_at, t.started_at, t.completed_at, t.result, t.error
FROM tasks t
INNER JOIN task_dependencies td ON t.id = td.depends_on
WHERE td.task_id = ?
`

func (q *Queries) GetTaskDependencies(ctx context.Context, taskID string) ([]Task, error) {
	rows, err := q.query(ctx, q.getTaskDependenciesStmt, getTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Priority,
			&i.ScheduledAt,
			&i.Deadline,
			&i.ScheduleExpr,
			&i.Agency,
			&i.Agent,
			&i.Skills,
			&i.Parameters,
			&i.Status,
			&i.Progress,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, name, description, type, priority, scheduled_at, deadline, schedule_expr, agency, agent, skills, parameters, status, progress, created_at, started_at, completed_at, result, error
FROM tasks
WHERE status IN (?, ?)
  AND (scheduled_at IS NULL OR scheduled_at <= ?)
ORDER BY priority DESC, created_at ASC
LIMIT 100
`

type ListPendingTasksParams struct {
	Status      string        `json:"status"`
	Status_2    string        `json:"status_2"`
	ScheduledAt sql.NullInt64 `json:"scheduled_at"`
}

func (q *Queries) ListPendingTasks(ctx context.Context, arg ListPendingTasksParams) ([]Task, error) {
	rows, err := q.query(ctx, q.listPendingTasksStmt, listPendingTasks, arg.Status, arg.Status_2, arg.ScheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Priority,
			&i.ScheduledAt,
			&i.Deadline,
			&i.ScheduleExpr,
			&i.Agency,
			&i.Agent,
			&i.Skills,
			&i.Parameters,
			&i.Status,
			&i.Progress,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, description, type, priority, scheduled_at, deadline, schedule_expr, agency, agent, skills, parameters, status, progress, created_at, started_at, completed_at, result, error
FROM tasks
ORDER BY priority DESC, created_at ASC
LIMIT ? OFFSET ?
`

type ListTasksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksStmt, listTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Priority,
			&i.ScheduledAt,
			&i.Deadline,
			&i.ScheduleExpr,
			&i.Agency,
			&i.Agent,
			&i.Skills,
			&i.Parameters,
			&i.Status,
			&i.Progress,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByAgency = `-- name: ListTasksByAgency :many
SELECT id, name, description, type, priority, scheduled_at, deadline, schedule_expr, agency, agent, skills, parameters, status, progress, created_at, started_at, completed_at, result, error
FROM tasks
WHERE agency = ?
ORDER BY priority DESC, created_at ASC
LIMIT ? OFFSET ?
`

type ListTasksByAgencyParams struct {
	Agency sql.NullString `json:"agency"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

func (q *Queries) ListTasksByAgency(ctx context.Context, arg ListTasksByAgencyParams) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksByAgencyStmt, listTasksByAgency, arg.Agency, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Priority,
			&i.ScheduledAt,
			&i.Deadline,
			&i.ScheduleExpr,
			&i.Agency,
			&i.Agent,
			&i.Skills,
			&i.Parameters,
			&i.Status,
			&i.Progress,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, name, description, type, priority, scheduled_at, deadline, schedule_expr, agency, agent, skills, parameters, status, progress, created_at, started_at, completed_at, result, error
FROM tasks
WHERE status = ?
ORDER BY priority DESC, created_at ASC
LIMIT ? OFFSET ?
`

type ListTasksByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksByStatusStmt, listTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Priority,
			&i.ScheduledAt,
			&i.Deadline,
			&i.ScheduleExpr,
			&i.Agency,
			&i.Agent,
			&i.Skills,
			&i.Parameters,
			&i.Status,
			&i.Progress,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskDependency = `-- name: RemoveTaskDependency :exec
DELETE FROM task_dependencies
WHERE task_id = ? AND depends_on = ?
`

type RemoveTaskDependencyParams struct {
	TaskID    string `json:"task_id"`
	DependsOn string `json:"depends_on"`
}

func (q *Queries) RemoveTaskDependency(ctx context.Context, arg RemoveTaskDependencyParams) error {
	_, err := q.exec(ctx, q.removeTaskDependencyStmt, removeTaskDependency, arg.TaskID, arg.DependsOn)
	return err
}

const updateTaskProgress = `-- name: UpdateTaskProgress :exec
UPDATE tasks
SET progress = ?
WHERE id = ?
`

type UpdateTaskProgressParams struct {
	Progress float64 `json:"progress"`
	ID       string  `json:"id"`
}

func (q *Queries) UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) error {
	_, err := q.exec(ctx, q.updateTaskProgressStmt, updateTaskProgress, arg.Progress, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = ?,
    started_at = CASE WHEN ? = 'running' AND started_at IS NULL THEN strftime('%s', 'now') ELSE started_at END,
    completed_at = CASE WHEN ? = 'completed' OR ? = 'failed' OR ? = 'cancelled' THEN strftime('%s', 'now') ELSE completed_at END,
    progress = ?,
    result = ?,
    error = ?
WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status   string         `json:"status"`
	Column2  interface{}    `json:"column_2"`
	Column3  interface{}    `json:"column_3"`
	Column4  interface{}    `json:"column_4"`
	Column5  interface{}    `json:"column_5"`
	Progress float64        `json:"progress"`
	Result   sql.NullString `json:"result"`
	Error    sql.NullString `json:"error"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.exec(ctx, q.updateTaskStatusStmt, updateTaskStatus,
		arg.Status,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Progress,
		arg.Result,
		arg.Error,
		arg.ID,
	)
	return err
}
